// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_badge.proto

package com.erban.main.proto;

public final class PbBadge {
  private PbBadge() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbBadgeResVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:allo.proto.PbBadgeResVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 resId = 1;</code>
     */
    long getResId();

    /**
     * <code>int32 badgeCode = 2;</code>
     */
    int getBadgeCode();

    /**
     * <code>int32 badgeType = 3;</code>
     */
    int getBadgeType();

    /**
     * <code>int32 isSale = 4;</code>
     */
    int getIsSale();

    /**
     * <code>int32 currencyType = 5;</code>
     */
    int getCurrencyType();

    /**
     * <code>double price = 6;</code>
     */
    double getPrice();

    /**
     * <code>int32 day = 7;</code>
     */
    int getDay();

    /**
     * <code>int32 status = 8;</code>
     */
    int getStatus();

    /**
     * <code>int32 badgeLevel = 9;</code>
     */
    int getBadgeLevel();

    /**
     * <code>string badgePicMin = 10;</code>
     */
    java.lang.String getBadgePicMin();
    /**
     * <code>string badgePicMin = 10;</code>
     */
    com.google.protobuf.ByteString
        getBadgePicMinBytes();

    /**
     * <code>string badgePicMax = 11;</code>
     */
    java.lang.String getBadgePicMax();
    /**
     * <code>string badgePicMax = 11;</code>
     */
    com.google.protobuf.ByteString
        getBadgePicMaxBytes();

    /**
     * <code>string badgeName = 12;</code>
     */
    java.lang.String getBadgeName();
    /**
     * <code>string badgeName = 12;</code>
     */
    com.google.protobuf.ByteString
        getBadgeNameBytes();

    /**
     * <code>string badgeDes = 13;</code>
     */
    java.lang.String getBadgeDes();
    /**
     * <code>string badgeDes = 13;</code>
     */
    com.google.protobuf.ByteString
        getBadgeDesBytes();

    /**
     * <pre>
     *是否已经拥有
     * </pre>
     *
     * <code>bool isOwn = 14;</code>
     */
    boolean getIsOwn();
  }
  /**
   * Protobuf type {@code allo.proto.PbBadgeResVo}
   */
  public  static final class PbBadgeResVo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:allo.proto.PbBadgeResVo)
      PbBadgeResVoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbBadgeResVo.newBuilder() to construct.
    private PbBadgeResVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbBadgeResVo() {
      badgePicMin_ = "";
      badgePicMax_ = "";
      badgeName_ = "";
      badgeDes_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbBadgeResVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              resId_ = input.readInt64();
              break;
            }
            case 16: {

              badgeCode_ = input.readInt32();
              break;
            }
            case 24: {

              badgeType_ = input.readInt32();
              break;
            }
            case 32: {

              isSale_ = input.readInt32();
              break;
            }
            case 40: {

              currencyType_ = input.readInt32();
              break;
            }
            case 49: {

              price_ = input.readDouble();
              break;
            }
            case 56: {

              day_ = input.readInt32();
              break;
            }
            case 64: {

              status_ = input.readInt32();
              break;
            }
            case 72: {

              badgeLevel_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              badgePicMin_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              badgePicMax_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              badgeName_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              badgeDes_ = s;
              break;
            }
            case 112: {

              isOwn_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erban.main.proto.PbBadge.internal_static_allo_proto_PbBadgeResVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erban.main.proto.PbBadge.internal_static_allo_proto_PbBadgeResVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erban.main.proto.PbBadge.PbBadgeResVo.class, com.erban.main.proto.PbBadge.PbBadgeResVo.Builder.class);
    }

    public static final int RESID_FIELD_NUMBER = 1;
    private long resId_;
    /**
     * <code>int64 resId = 1;</code>
     */
    public long getResId() {
      return resId_;
    }

    public static final int BADGECODE_FIELD_NUMBER = 2;
    private int badgeCode_;
    /**
     * <code>int32 badgeCode = 2;</code>
     */
    public int getBadgeCode() {
      return badgeCode_;
    }

    public static final int BADGETYPE_FIELD_NUMBER = 3;
    private int badgeType_;
    /**
     * <code>int32 badgeType = 3;</code>
     */
    public int getBadgeType() {
      return badgeType_;
    }

    public static final int ISSALE_FIELD_NUMBER = 4;
    private int isSale_;
    /**
     * <code>int32 isSale = 4;</code>
     */
    public int getIsSale() {
      return isSale_;
    }

    public static final int CURRENCYTYPE_FIELD_NUMBER = 5;
    private int currencyType_;
    /**
     * <code>int32 currencyType = 5;</code>
     */
    public int getCurrencyType() {
      return currencyType_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_;
    /**
     * <code>double price = 6;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int DAY_FIELD_NUMBER = 7;
    private int day_;
    /**
     * <code>int32 day = 7;</code>
     */
    public int getDay() {
      return day_;
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>int32 status = 8;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int BADGELEVEL_FIELD_NUMBER = 9;
    private int badgeLevel_;
    /**
     * <code>int32 badgeLevel = 9;</code>
     */
    public int getBadgeLevel() {
      return badgeLevel_;
    }

    public static final int BADGEPICMIN_FIELD_NUMBER = 10;
    private volatile java.lang.Object badgePicMin_;
    /**
     * <code>string badgePicMin = 10;</code>
     */
    public java.lang.String getBadgePicMin() {
      java.lang.Object ref = badgePicMin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        badgePicMin_ = s;
        return s;
      }
    }
    /**
     * <code>string badgePicMin = 10;</code>
     */
    public com.google.protobuf.ByteString
        getBadgePicMinBytes() {
      java.lang.Object ref = badgePicMin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        badgePicMin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BADGEPICMAX_FIELD_NUMBER = 11;
    private volatile java.lang.Object badgePicMax_;
    /**
     * <code>string badgePicMax = 11;</code>
     */
    public java.lang.String getBadgePicMax() {
      java.lang.Object ref = badgePicMax_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        badgePicMax_ = s;
        return s;
      }
    }
    /**
     * <code>string badgePicMax = 11;</code>
     */
    public com.google.protobuf.ByteString
        getBadgePicMaxBytes() {
      java.lang.Object ref = badgePicMax_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        badgePicMax_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BADGENAME_FIELD_NUMBER = 12;
    private volatile java.lang.Object badgeName_;
    /**
     * <code>string badgeName = 12;</code>
     */
    public java.lang.String getBadgeName() {
      java.lang.Object ref = badgeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        badgeName_ = s;
        return s;
      }
    }
    /**
     * <code>string badgeName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getBadgeNameBytes() {
      java.lang.Object ref = badgeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        badgeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BADGEDES_FIELD_NUMBER = 13;
    private volatile java.lang.Object badgeDes_;
    /**
     * <code>string badgeDes = 13;</code>
     */
    public java.lang.String getBadgeDes() {
      java.lang.Object ref = badgeDes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        badgeDes_ = s;
        return s;
      }
    }
    /**
     * <code>string badgeDes = 13;</code>
     */
    public com.google.protobuf.ByteString
        getBadgeDesBytes() {
      java.lang.Object ref = badgeDes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        badgeDes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISOWN_FIELD_NUMBER = 14;
    private boolean isOwn_;
    /**
     * <pre>
     *是否已经拥有
     * </pre>
     *
     * <code>bool isOwn = 14;</code>
     */
    public boolean getIsOwn() {
      return isOwn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resId_ != 0L) {
        output.writeInt64(1, resId_);
      }
      if (badgeCode_ != 0) {
        output.writeInt32(2, badgeCode_);
      }
      if (badgeType_ != 0) {
        output.writeInt32(3, badgeType_);
      }
      if (isSale_ != 0) {
        output.writeInt32(4, isSale_);
      }
      if (currencyType_ != 0) {
        output.writeInt32(5, currencyType_);
      }
      if (price_ != 0D) {
        output.writeDouble(6, price_);
      }
      if (day_ != 0) {
        output.writeInt32(7, day_);
      }
      if (status_ != 0) {
        output.writeInt32(8, status_);
      }
      if (badgeLevel_ != 0) {
        output.writeInt32(9, badgeLevel_);
      }
      if (!getBadgePicMinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, badgePicMin_);
      }
      if (!getBadgePicMaxBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, badgePicMax_);
      }
      if (!getBadgeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, badgeName_);
      }
      if (!getBadgeDesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, badgeDes_);
      }
      if (isOwn_ != false) {
        output.writeBool(14, isOwn_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, resId_);
      }
      if (badgeCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, badgeCode_);
      }
      if (badgeType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, badgeType_);
      }
      if (isSale_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, isSale_);
      }
      if (currencyType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, currencyType_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, day_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, status_);
      }
      if (badgeLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, badgeLevel_);
      }
      if (!getBadgePicMinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, badgePicMin_);
      }
      if (!getBadgePicMaxBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, badgePicMax_);
      }
      if (!getBadgeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, badgeName_);
      }
      if (!getBadgeDesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, badgeDes_);
      }
      if (isOwn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, isOwn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.erban.main.proto.PbBadge.PbBadgeResVo)) {
        return super.equals(obj);
      }
      com.erban.main.proto.PbBadge.PbBadgeResVo other = (com.erban.main.proto.PbBadge.PbBadgeResVo) obj;

      if (getResId()
          != other.getResId()) return false;
      if (getBadgeCode()
          != other.getBadgeCode()) return false;
      if (getBadgeType()
          != other.getBadgeType()) return false;
      if (getIsSale()
          != other.getIsSale()) return false;
      if (getCurrencyType()
          != other.getCurrencyType()) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (getDay()
          != other.getDay()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (getBadgeLevel()
          != other.getBadgeLevel()) return false;
      if (!getBadgePicMin()
          .equals(other.getBadgePicMin())) return false;
      if (!getBadgePicMax()
          .equals(other.getBadgePicMax())) return false;
      if (!getBadgeName()
          .equals(other.getBadgeName())) return false;
      if (!getBadgeDes()
          .equals(other.getBadgeDes())) return false;
      if (getIsOwn()
          != other.getIsOwn()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResId());
      hash = (37 * hash) + BADGECODE_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeCode();
      hash = (37 * hash) + BADGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeType();
      hash = (37 * hash) + ISSALE_FIELD_NUMBER;
      hash = (53 * hash) + getIsSale();
      hash = (37 * hash) + CURRENCYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyType();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + BADGELEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeLevel();
      hash = (37 * hash) + BADGEPICMIN_FIELD_NUMBER;
      hash = (53 * hash) + getBadgePicMin().hashCode();
      hash = (37 * hash) + BADGEPICMAX_FIELD_NUMBER;
      hash = (53 * hash) + getBadgePicMax().hashCode();
      hash = (37 * hash) + BADGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeName().hashCode();
      hash = (37 * hash) + BADGEDES_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeDes().hashCode();
      hash = (37 * hash) + ISOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOwn());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbBadge.PbBadgeResVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.erban.main.proto.PbBadge.PbBadgeResVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code allo.proto.PbBadgeResVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:allo.proto.PbBadgeResVo)
        com.erban.main.proto.PbBadge.PbBadgeResVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.erban.main.proto.PbBadge.internal_static_allo_proto_PbBadgeResVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.erban.main.proto.PbBadge.internal_static_allo_proto_PbBadgeResVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.erban.main.proto.PbBadge.PbBadgeResVo.class, com.erban.main.proto.PbBadge.PbBadgeResVo.Builder.class);
      }

      // Construct using com.erban.main.proto.PbBadge.PbBadgeResVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resId_ = 0L;

        badgeCode_ = 0;

        badgeType_ = 0;

        isSale_ = 0;

        currencyType_ = 0;

        price_ = 0D;

        day_ = 0;

        status_ = 0;

        badgeLevel_ = 0;

        badgePicMin_ = "";

        badgePicMax_ = "";

        badgeName_ = "";

        badgeDes_ = "";

        isOwn_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.erban.main.proto.PbBadge.internal_static_allo_proto_PbBadgeResVo_descriptor;
      }

      @java.lang.Override
      public com.erban.main.proto.PbBadge.PbBadgeResVo getDefaultInstanceForType() {
        return com.erban.main.proto.PbBadge.PbBadgeResVo.getDefaultInstance();
      }

      @java.lang.Override
      public com.erban.main.proto.PbBadge.PbBadgeResVo build() {
        com.erban.main.proto.PbBadge.PbBadgeResVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.erban.main.proto.PbBadge.PbBadgeResVo buildPartial() {
        com.erban.main.proto.PbBadge.PbBadgeResVo result = new com.erban.main.proto.PbBadge.PbBadgeResVo(this);
        result.resId_ = resId_;
        result.badgeCode_ = badgeCode_;
        result.badgeType_ = badgeType_;
        result.isSale_ = isSale_;
        result.currencyType_ = currencyType_;
        result.price_ = price_;
        result.day_ = day_;
        result.status_ = status_;
        result.badgeLevel_ = badgeLevel_;
        result.badgePicMin_ = badgePicMin_;
        result.badgePicMax_ = badgePicMax_;
        result.badgeName_ = badgeName_;
        result.badgeDes_ = badgeDes_;
        result.isOwn_ = isOwn_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.erban.main.proto.PbBadge.PbBadgeResVo) {
          return mergeFrom((com.erban.main.proto.PbBadge.PbBadgeResVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.erban.main.proto.PbBadge.PbBadgeResVo other) {
        if (other == com.erban.main.proto.PbBadge.PbBadgeResVo.getDefaultInstance()) return this;
        if (other.getResId() != 0L) {
          setResId(other.getResId());
        }
        if (other.getBadgeCode() != 0) {
          setBadgeCode(other.getBadgeCode());
        }
        if (other.getBadgeType() != 0) {
          setBadgeType(other.getBadgeType());
        }
        if (other.getIsSale() != 0) {
          setIsSale(other.getIsSale());
        }
        if (other.getCurrencyType() != 0) {
          setCurrencyType(other.getCurrencyType());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getBadgeLevel() != 0) {
          setBadgeLevel(other.getBadgeLevel());
        }
        if (!other.getBadgePicMin().isEmpty()) {
          badgePicMin_ = other.badgePicMin_;
          onChanged();
        }
        if (!other.getBadgePicMax().isEmpty()) {
          badgePicMax_ = other.badgePicMax_;
          onChanged();
        }
        if (!other.getBadgeName().isEmpty()) {
          badgeName_ = other.badgeName_;
          onChanged();
        }
        if (!other.getBadgeDes().isEmpty()) {
          badgeDes_ = other.badgeDes_;
          onChanged();
        }
        if (other.getIsOwn() != false) {
          setIsOwn(other.getIsOwn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.erban.main.proto.PbBadge.PbBadgeResVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.erban.main.proto.PbBadge.PbBadgeResVo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long resId_ ;
      /**
       * <code>int64 resId = 1;</code>
       */
      public long getResId() {
        return resId_;
      }
      /**
       * <code>int64 resId = 1;</code>
       */
      public Builder setResId(long value) {
        
        resId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 resId = 1;</code>
       */
      public Builder clearResId() {
        
        resId_ = 0L;
        onChanged();
        return this;
      }

      private int badgeCode_ ;
      /**
       * <code>int32 badgeCode = 2;</code>
       */
      public int getBadgeCode() {
        return badgeCode_;
      }
      /**
       * <code>int32 badgeCode = 2;</code>
       */
      public Builder setBadgeCode(int value) {
        
        badgeCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 badgeCode = 2;</code>
       */
      public Builder clearBadgeCode() {
        
        badgeCode_ = 0;
        onChanged();
        return this;
      }

      private int badgeType_ ;
      /**
       * <code>int32 badgeType = 3;</code>
       */
      public int getBadgeType() {
        return badgeType_;
      }
      /**
       * <code>int32 badgeType = 3;</code>
       */
      public Builder setBadgeType(int value) {
        
        badgeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 badgeType = 3;</code>
       */
      public Builder clearBadgeType() {
        
        badgeType_ = 0;
        onChanged();
        return this;
      }

      private int isSale_ ;
      /**
       * <code>int32 isSale = 4;</code>
       */
      public int getIsSale() {
        return isSale_;
      }
      /**
       * <code>int32 isSale = 4;</code>
       */
      public Builder setIsSale(int value) {
        
        isSale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 isSale = 4;</code>
       */
      public Builder clearIsSale() {
        
        isSale_ = 0;
        onChanged();
        return this;
      }

      private int currencyType_ ;
      /**
       * <code>int32 currencyType = 5;</code>
       */
      public int getCurrencyType() {
        return currencyType_;
      }
      /**
       * <code>int32 currencyType = 5;</code>
       */
      public Builder setCurrencyType(int value) {
        
        currencyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currencyType = 5;</code>
       */
      public Builder clearCurrencyType() {
        
        currencyType_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 6;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 6;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 6;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <code>int32 day = 7;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>int32 day = 7;</code>
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 day = 7;</code>
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 8;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 8;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 8;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int badgeLevel_ ;
      /**
       * <code>int32 badgeLevel = 9;</code>
       */
      public int getBadgeLevel() {
        return badgeLevel_;
      }
      /**
       * <code>int32 badgeLevel = 9;</code>
       */
      public Builder setBadgeLevel(int value) {
        
        badgeLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 badgeLevel = 9;</code>
       */
      public Builder clearBadgeLevel() {
        
        badgeLevel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object badgePicMin_ = "";
      /**
       * <code>string badgePicMin = 10;</code>
       */
      public java.lang.String getBadgePicMin() {
        java.lang.Object ref = badgePicMin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          badgePicMin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string badgePicMin = 10;</code>
       */
      public com.google.protobuf.ByteString
          getBadgePicMinBytes() {
        java.lang.Object ref = badgePicMin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          badgePicMin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string badgePicMin = 10;</code>
       */
      public Builder setBadgePicMin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        badgePicMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string badgePicMin = 10;</code>
       */
      public Builder clearBadgePicMin() {
        
        badgePicMin_ = getDefaultInstance().getBadgePicMin();
        onChanged();
        return this;
      }
      /**
       * <code>string badgePicMin = 10;</code>
       */
      public Builder setBadgePicMinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        badgePicMin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object badgePicMax_ = "";
      /**
       * <code>string badgePicMax = 11;</code>
       */
      public java.lang.String getBadgePicMax() {
        java.lang.Object ref = badgePicMax_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          badgePicMax_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string badgePicMax = 11;</code>
       */
      public com.google.protobuf.ByteString
          getBadgePicMaxBytes() {
        java.lang.Object ref = badgePicMax_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          badgePicMax_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string badgePicMax = 11;</code>
       */
      public Builder setBadgePicMax(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        badgePicMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string badgePicMax = 11;</code>
       */
      public Builder clearBadgePicMax() {
        
        badgePicMax_ = getDefaultInstance().getBadgePicMax();
        onChanged();
        return this;
      }
      /**
       * <code>string badgePicMax = 11;</code>
       */
      public Builder setBadgePicMaxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        badgePicMax_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object badgeName_ = "";
      /**
       * <code>string badgeName = 12;</code>
       */
      public java.lang.String getBadgeName() {
        java.lang.Object ref = badgeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          badgeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string badgeName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getBadgeNameBytes() {
        java.lang.Object ref = badgeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          badgeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string badgeName = 12;</code>
       */
      public Builder setBadgeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        badgeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string badgeName = 12;</code>
       */
      public Builder clearBadgeName() {
        
        badgeName_ = getDefaultInstance().getBadgeName();
        onChanged();
        return this;
      }
      /**
       * <code>string badgeName = 12;</code>
       */
      public Builder setBadgeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        badgeName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object badgeDes_ = "";
      /**
       * <code>string badgeDes = 13;</code>
       */
      public java.lang.String getBadgeDes() {
        java.lang.Object ref = badgeDes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          badgeDes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string badgeDes = 13;</code>
       */
      public com.google.protobuf.ByteString
          getBadgeDesBytes() {
        java.lang.Object ref = badgeDes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          badgeDes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string badgeDes = 13;</code>
       */
      public Builder setBadgeDes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        badgeDes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string badgeDes = 13;</code>
       */
      public Builder clearBadgeDes() {
        
        badgeDes_ = getDefaultInstance().getBadgeDes();
        onChanged();
        return this;
      }
      /**
       * <code>string badgeDes = 13;</code>
       */
      public Builder setBadgeDesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        badgeDes_ = value;
        onChanged();
        return this;
      }

      private boolean isOwn_ ;
      /**
       * <pre>
       *是否已经拥有
       * </pre>
       *
       * <code>bool isOwn = 14;</code>
       */
      public boolean getIsOwn() {
        return isOwn_;
      }
      /**
       * <pre>
       *是否已经拥有
       * </pre>
       *
       * <code>bool isOwn = 14;</code>
       */
      public Builder setIsOwn(boolean value) {
        
        isOwn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否已经拥有
       * </pre>
       *
       * <code>bool isOwn = 14;</code>
       */
      public Builder clearIsOwn() {
        
        isOwn_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:allo.proto.PbBadgeResVo)
    }

    // @@protoc_insertion_point(class_scope:allo.proto.PbBadgeResVo)
    private static final com.erban.main.proto.PbBadge.PbBadgeResVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.erban.main.proto.PbBadge.PbBadgeResVo();
    }

    public static com.erban.main.proto.PbBadge.PbBadgeResVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbBadgeResVo>
        PARSER = new com.google.protobuf.AbstractParser<PbBadgeResVo>() {
      @java.lang.Override
      public PbBadgeResVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbBadgeResVo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbBadgeResVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbBadgeResVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.erban.main.proto.PbBadge.PbBadgeResVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allo_proto_PbBadgeResVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allo_proto_PbBadgeResVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pb_badge.proto\022\nallo.proto\"\207\002\n\014PbBadge" +
      "ResVo\022\r\n\005resId\030\001 \001(\003\022\021\n\tbadgeCode\030\002 \001(\005\022" +
      "\021\n\tbadgeType\030\003 \001(\005\022\016\n\006isSale\030\004 \001(\005\022\024\n\014cu" +
      "rrencyType\030\005 \001(\005\022\r\n\005price\030\006 \001(\001\022\013\n\003day\030\007" +
      " \001(\005\022\016\n\006status\030\010 \001(\005\022\022\n\nbadgeLevel\030\t \001(\005" +
      "\022\023\n\013badgePicMin\030\n \001(\t\022\023\n\013badgePicMax\030\013 \001" +
      "(\t\022\021\n\tbadgeName\030\014 \001(\t\022\020\n\010badgeDes\030\r \001(\t\022" +
      "\r\n\005isOwn\030\016 \001(\010B\026\n\024com.erban.main.protob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_allo_proto_PbBadgeResVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_allo_proto_PbBadgeResVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allo_proto_PbBadgeResVo_descriptor,
        new java.lang.String[] { "ResId", "BadgeCode", "BadgeType", "IsSale", "CurrencyType", "Price", "Day", "Status", "BadgeLevel", "BadgePicMin", "BadgePicMax", "BadgeName", "BadgeDes", "IsOwn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
