// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_gift.proto

package com.erban.main.proto;

public final class PbGift {
  private PbGift() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GiftVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:allo.proto.GiftVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 giftId = 1;</code>
     */
    int getGiftId();

    /**
     * <code>string giftName = 2;</code>
     */
    java.lang.String getGiftName();
    /**
     * <code>string giftName = 2;</code>
     */
    com.google.protobuf.ByteString
        getGiftNameBytes();

    /**
     * <code>double goldPrice = 3;</code>
     */
    double getGoldPrice();

    /**
     * <code>string giftUrl = 4;</code>
     */
    java.lang.String getGiftUrl();
    /**
     * <code>string giftUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getGiftUrlBytes();

    /**
     * <code>int32 nobleId = 5;</code>
     */
    int getNobleId();

    /**
     * <code>string nobleName = 6;</code>
     */
    java.lang.String getNobleName();
    /**
     * <code>string nobleName = 6;</code>
     */
    com.google.protobuf.ByteString
        getNobleNameBytes();

    /**
     * <code>bool isNobleGift = 7;</code>
     */
    boolean getIsNobleGift();

    /**
     * <code>int32 seqNo = 8;</code>
     */
    int getSeqNo();

    /**
     * <code>bool hasGifPic = 9;</code>
     */
    boolean getHasGifPic();

    /**
     * <code>int32 giftType = 10;</code>
     */
    int getGiftType();

    /**
     * <code>string gifUrl = 11;</code>
     */
    java.lang.String getGifUrl();
    /**
     * <code>string gifUrl = 11;</code>
     */
    com.google.protobuf.ByteString
        getGifUrlBytes();

    /**
     * <pre>
     *是否有vgg动画
     * </pre>
     *
     * <code>bool hasVggPic = 12;</code>
     */
    boolean getHasVggPic();

    /**
     * <pre>
     *vgg动画链接
     * </pre>
     *
     * <code>string vggUrl = 13;</code>
     */
    java.lang.String getVggUrl();
    /**
     * <pre>
     *vgg动画链接
     * </pre>
     *
     * <code>string vggUrl = 13;</code>
     */
    com.google.protobuf.ByteString
        getVggUrlBytes();

    /**
     * <pre>
     *是否是最新礼物
     * </pre>
     *
     * <code>bool hasLatest = 14;</code>
     */
    boolean getHasLatest();

    /**
     * <pre>
     *是否是限时礼物
     * </pre>
     *
     * <code>bool hasTimeLimit = 15;</code>
     */
    boolean getHasTimeLimit();

    /**
     * <pre>
     *是否有特效
     * </pre>
     *
     * <code>bool hasEffect = 16;</code>
     */
    boolean getHasEffect();

    /**
     * <pre>
     ** 是否CP礼物 
     * </pre>
     *
     * <code>bool hasCp = 17;</code>
     */
    boolean getHasCp();

    /**
     * <pre>
     *是否全服通知
     * </pre>
     *
     * <code>bool isWholeServer = 18;</code>
     */
    boolean getIsWholeServer();

    /**
     * <pre>
     * 全服通知是否支持房间跳转
     * </pre>
     *
     * <code>bool isSkipRoom = 19;</code>
     */
    boolean getIsSkipRoom();

    /**
     * <pre>
     * 全服通知是否支持文字编辑
     * </pre>
     *
     * <code>bool isSendMsg = 20;</code>
     */
    boolean getIsSendMsg();

    /**
     * <pre>
     *消费类型，1：金币礼物，2：萝卜礼物
     * </pre>
     *
     * <code>int32 consumeType = 21;</code>
     */
    int getConsumeType();

    /**
     * <code>int32 giftIsSound = 22;</code>
     */
    int getGiftIsSound();

    /**
     * <pre>
     *0.无1.普通收送礼人头像2.冠名用户头像3.CP用户头像
     * </pre>
     *
     * <code>int32 giftAvatarShowType = 23;</code>
     */
    int getGiftAvatarShowType();

    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    java.util.List<com.erban.main.proto.PbUser.PbUsers> 
        getUserInfoList();
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    com.erban.main.proto.PbUser.PbUsers getUserInfo(int index);
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    int getUserInfoCount();
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    java.util.List<? extends com.erban.main.proto.PbUser.PbUsersOrBuilder> 
        getUserInfoOrBuilderList();
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    com.erban.main.proto.PbUser.PbUsersOrBuilder getUserInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code allo.proto.GiftVo}
   */
  public  static final class GiftVo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:allo.proto.GiftVo)
      GiftVoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GiftVo.newBuilder() to construct.
    private GiftVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GiftVo() {
      giftName_ = "";
      giftUrl_ = "";
      nobleName_ = "";
      gifUrl_ = "";
      vggUrl_ = "";
      userInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GiftVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              giftId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              giftName_ = s;
              break;
            }
            case 25: {

              goldPrice_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              giftUrl_ = s;
              break;
            }
            case 40: {

              nobleId_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              nobleName_ = s;
              break;
            }
            case 56: {

              isNobleGift_ = input.readBool();
              break;
            }
            case 64: {

              seqNo_ = input.readInt32();
              break;
            }
            case 72: {

              hasGifPic_ = input.readBool();
              break;
            }
            case 80: {

              giftType_ = input.readInt32();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              gifUrl_ = s;
              break;
            }
            case 96: {

              hasVggPic_ = input.readBool();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              vggUrl_ = s;
              break;
            }
            case 112: {

              hasLatest_ = input.readBool();
              break;
            }
            case 120: {

              hasTimeLimit_ = input.readBool();
              break;
            }
            case 128: {

              hasEffect_ = input.readBool();
              break;
            }
            case 136: {

              hasCp_ = input.readBool();
              break;
            }
            case 144: {

              isWholeServer_ = input.readBool();
              break;
            }
            case 152: {

              isSkipRoom_ = input.readBool();
              break;
            }
            case 160: {

              isSendMsg_ = input.readBool();
              break;
            }
            case 168: {

              consumeType_ = input.readInt32();
              break;
            }
            case 176: {

              giftIsSound_ = input.readInt32();
              break;
            }
            case 184: {

              giftAvatarShowType_ = input.readInt32();
              break;
            }
            case 194: {
              if (!((mutable_bitField0_ & 0x00800000) != 0)) {
                userInfo_ = new java.util.ArrayList<com.erban.main.proto.PbUser.PbUsers>();
                mutable_bitField0_ |= 0x00800000;
              }
              userInfo_.add(
                  input.readMessage(com.erban.main.proto.PbUser.PbUsers.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00800000) != 0)) {
          userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erban.main.proto.PbGift.internal_static_allo_proto_GiftVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erban.main.proto.PbGift.internal_static_allo_proto_GiftVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erban.main.proto.PbGift.GiftVo.class, com.erban.main.proto.PbGift.GiftVo.Builder.class);
    }

    private int bitField0_;
    public static final int GIFTID_FIELD_NUMBER = 1;
    private int giftId_;
    /**
     * <code>int32 giftId = 1;</code>
     */
    public int getGiftId() {
      return giftId_;
    }

    public static final int GIFTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object giftName_;
    /**
     * <code>string giftName = 2;</code>
     */
    public java.lang.String getGiftName() {
      java.lang.Object ref = giftName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        giftName_ = s;
        return s;
      }
    }
    /**
     * <code>string giftName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGiftNameBytes() {
      java.lang.Object ref = giftName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        giftName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOLDPRICE_FIELD_NUMBER = 3;
    private double goldPrice_;
    /**
     * <code>double goldPrice = 3;</code>
     */
    public double getGoldPrice() {
      return goldPrice_;
    }

    public static final int GIFTURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object giftUrl_;
    /**
     * <code>string giftUrl = 4;</code>
     */
    public java.lang.String getGiftUrl() {
      java.lang.Object ref = giftUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        giftUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string giftUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGiftUrlBytes() {
      java.lang.Object ref = giftUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        giftUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOBLEID_FIELD_NUMBER = 5;
    private int nobleId_;
    /**
     * <code>int32 nobleId = 5;</code>
     */
    public int getNobleId() {
      return nobleId_;
    }

    public static final int NOBLENAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object nobleName_;
    /**
     * <code>string nobleName = 6;</code>
     */
    public java.lang.String getNobleName() {
      java.lang.Object ref = nobleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nobleName_ = s;
        return s;
      }
    }
    /**
     * <code>string nobleName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNobleNameBytes() {
      java.lang.Object ref = nobleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nobleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISNOBLEGIFT_FIELD_NUMBER = 7;
    private boolean isNobleGift_;
    /**
     * <code>bool isNobleGift = 7;</code>
     */
    public boolean getIsNobleGift() {
      return isNobleGift_;
    }

    public static final int SEQNO_FIELD_NUMBER = 8;
    private int seqNo_;
    /**
     * <code>int32 seqNo = 8;</code>
     */
    public int getSeqNo() {
      return seqNo_;
    }

    public static final int HASGIFPIC_FIELD_NUMBER = 9;
    private boolean hasGifPic_;
    /**
     * <code>bool hasGifPic = 9;</code>
     */
    public boolean getHasGifPic() {
      return hasGifPic_;
    }

    public static final int GIFTTYPE_FIELD_NUMBER = 10;
    private int giftType_;
    /**
     * <code>int32 giftType = 10;</code>
     */
    public int getGiftType() {
      return giftType_;
    }

    public static final int GIFURL_FIELD_NUMBER = 11;
    private volatile java.lang.Object gifUrl_;
    /**
     * <code>string gifUrl = 11;</code>
     */
    public java.lang.String getGifUrl() {
      java.lang.Object ref = gifUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gifUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string gifUrl = 11;</code>
     */
    public com.google.protobuf.ByteString
        getGifUrlBytes() {
      java.lang.Object ref = gifUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gifUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASVGGPIC_FIELD_NUMBER = 12;
    private boolean hasVggPic_;
    /**
     * <pre>
     *是否有vgg动画
     * </pre>
     *
     * <code>bool hasVggPic = 12;</code>
     */
    public boolean getHasVggPic() {
      return hasVggPic_;
    }

    public static final int VGGURL_FIELD_NUMBER = 13;
    private volatile java.lang.Object vggUrl_;
    /**
     * <pre>
     *vgg动画链接
     * </pre>
     *
     * <code>string vggUrl = 13;</code>
     */
    public java.lang.String getVggUrl() {
      java.lang.Object ref = vggUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vggUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *vgg动画链接
     * </pre>
     *
     * <code>string vggUrl = 13;</code>
     */
    public com.google.protobuf.ByteString
        getVggUrlBytes() {
      java.lang.Object ref = vggUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vggUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASLATEST_FIELD_NUMBER = 14;
    private boolean hasLatest_;
    /**
     * <pre>
     *是否是最新礼物
     * </pre>
     *
     * <code>bool hasLatest = 14;</code>
     */
    public boolean getHasLatest() {
      return hasLatest_;
    }

    public static final int HASTIMELIMIT_FIELD_NUMBER = 15;
    private boolean hasTimeLimit_;
    /**
     * <pre>
     *是否是限时礼物
     * </pre>
     *
     * <code>bool hasTimeLimit = 15;</code>
     */
    public boolean getHasTimeLimit() {
      return hasTimeLimit_;
    }

    public static final int HASEFFECT_FIELD_NUMBER = 16;
    private boolean hasEffect_;
    /**
     * <pre>
     *是否有特效
     * </pre>
     *
     * <code>bool hasEffect = 16;</code>
     */
    public boolean getHasEffect() {
      return hasEffect_;
    }

    public static final int HASCP_FIELD_NUMBER = 17;
    private boolean hasCp_;
    /**
     * <pre>
     ** 是否CP礼物 
     * </pre>
     *
     * <code>bool hasCp = 17;</code>
     */
    public boolean getHasCp() {
      return hasCp_;
    }

    public static final int ISWHOLESERVER_FIELD_NUMBER = 18;
    private boolean isWholeServer_;
    /**
     * <pre>
     *是否全服通知
     * </pre>
     *
     * <code>bool isWholeServer = 18;</code>
     */
    public boolean getIsWholeServer() {
      return isWholeServer_;
    }

    public static final int ISSKIPROOM_FIELD_NUMBER = 19;
    private boolean isSkipRoom_;
    /**
     * <pre>
     * 全服通知是否支持房间跳转
     * </pre>
     *
     * <code>bool isSkipRoom = 19;</code>
     */
    public boolean getIsSkipRoom() {
      return isSkipRoom_;
    }

    public static final int ISSENDMSG_FIELD_NUMBER = 20;
    private boolean isSendMsg_;
    /**
     * <pre>
     * 全服通知是否支持文字编辑
     * </pre>
     *
     * <code>bool isSendMsg = 20;</code>
     */
    public boolean getIsSendMsg() {
      return isSendMsg_;
    }

    public static final int CONSUMETYPE_FIELD_NUMBER = 21;
    private int consumeType_;
    /**
     * <pre>
     *消费类型，1：金币礼物，2：萝卜礼物
     * </pre>
     *
     * <code>int32 consumeType = 21;</code>
     */
    public int getConsumeType() {
      return consumeType_;
    }

    public static final int GIFTISSOUND_FIELD_NUMBER = 22;
    private int giftIsSound_;
    /**
     * <code>int32 giftIsSound = 22;</code>
     */
    public int getGiftIsSound() {
      return giftIsSound_;
    }

    public static final int GIFTAVATARSHOWTYPE_FIELD_NUMBER = 23;
    private int giftAvatarShowType_;
    /**
     * <pre>
     *0.无1.普通收送礼人头像2.冠名用户头像3.CP用户头像
     * </pre>
     *
     * <code>int32 giftAvatarShowType = 23;</code>
     */
    public int getGiftAvatarShowType() {
      return giftAvatarShowType_;
    }

    public static final int USERINFO_FIELD_NUMBER = 24;
    private java.util.List<com.erban.main.proto.PbUser.PbUsers> userInfo_;
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    public java.util.List<com.erban.main.proto.PbUser.PbUsers> getUserInfoList() {
      return userInfo_;
    }
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    public java.util.List<? extends com.erban.main.proto.PbUser.PbUsersOrBuilder> 
        getUserInfoOrBuilderList() {
      return userInfo_;
    }
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    public int getUserInfoCount() {
      return userInfo_.size();
    }
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    public com.erban.main.proto.PbUser.PbUsers getUserInfo(int index) {
      return userInfo_.get(index);
    }
    /**
     * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
     */
    public com.erban.main.proto.PbUser.PbUsersOrBuilder getUserInfoOrBuilder(
        int index) {
      return userInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (giftId_ != 0) {
        output.writeInt32(1, giftId_);
      }
      if (!getGiftNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, giftName_);
      }
      if (goldPrice_ != 0D) {
        output.writeDouble(3, goldPrice_);
      }
      if (!getGiftUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, giftUrl_);
      }
      if (nobleId_ != 0) {
        output.writeInt32(5, nobleId_);
      }
      if (!getNobleNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nobleName_);
      }
      if (isNobleGift_ != false) {
        output.writeBool(7, isNobleGift_);
      }
      if (seqNo_ != 0) {
        output.writeInt32(8, seqNo_);
      }
      if (hasGifPic_ != false) {
        output.writeBool(9, hasGifPic_);
      }
      if (giftType_ != 0) {
        output.writeInt32(10, giftType_);
      }
      if (!getGifUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, gifUrl_);
      }
      if (hasVggPic_ != false) {
        output.writeBool(12, hasVggPic_);
      }
      if (!getVggUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, vggUrl_);
      }
      if (hasLatest_ != false) {
        output.writeBool(14, hasLatest_);
      }
      if (hasTimeLimit_ != false) {
        output.writeBool(15, hasTimeLimit_);
      }
      if (hasEffect_ != false) {
        output.writeBool(16, hasEffect_);
      }
      if (hasCp_ != false) {
        output.writeBool(17, hasCp_);
      }
      if (isWholeServer_ != false) {
        output.writeBool(18, isWholeServer_);
      }
      if (isSkipRoom_ != false) {
        output.writeBool(19, isSkipRoom_);
      }
      if (isSendMsg_ != false) {
        output.writeBool(20, isSendMsg_);
      }
      if (consumeType_ != 0) {
        output.writeInt32(21, consumeType_);
      }
      if (giftIsSound_ != 0) {
        output.writeInt32(22, giftIsSound_);
      }
      if (giftAvatarShowType_ != 0) {
        output.writeInt32(23, giftAvatarShowType_);
      }
      for (int i = 0; i < userInfo_.size(); i++) {
        output.writeMessage(24, userInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (giftId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, giftId_);
      }
      if (!getGiftNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, giftName_);
      }
      if (goldPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, goldPrice_);
      }
      if (!getGiftUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, giftUrl_);
      }
      if (nobleId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, nobleId_);
      }
      if (!getNobleNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nobleName_);
      }
      if (isNobleGift_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isNobleGift_);
      }
      if (seqNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, seqNo_);
      }
      if (hasGifPic_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, hasGifPic_);
      }
      if (giftType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, giftType_);
      }
      if (!getGifUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, gifUrl_);
      }
      if (hasVggPic_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, hasVggPic_);
      }
      if (!getVggUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, vggUrl_);
      }
      if (hasLatest_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, hasLatest_);
      }
      if (hasTimeLimit_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, hasTimeLimit_);
      }
      if (hasEffect_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, hasEffect_);
      }
      if (hasCp_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, hasCp_);
      }
      if (isWholeServer_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(18, isWholeServer_);
      }
      if (isSkipRoom_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(19, isSkipRoom_);
      }
      if (isSendMsg_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, isSendMsg_);
      }
      if (consumeType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, consumeType_);
      }
      if (giftIsSound_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, giftIsSound_);
      }
      if (giftAvatarShowType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, giftAvatarShowType_);
      }
      for (int i = 0; i < userInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(24, userInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.erban.main.proto.PbGift.GiftVo)) {
        return super.equals(obj);
      }
      com.erban.main.proto.PbGift.GiftVo other = (com.erban.main.proto.PbGift.GiftVo) obj;

      if (getGiftId()
          != other.getGiftId()) return false;
      if (!getGiftName()
          .equals(other.getGiftName())) return false;
      if (java.lang.Double.doubleToLongBits(getGoldPrice())
          != java.lang.Double.doubleToLongBits(
              other.getGoldPrice())) return false;
      if (!getGiftUrl()
          .equals(other.getGiftUrl())) return false;
      if (getNobleId()
          != other.getNobleId()) return false;
      if (!getNobleName()
          .equals(other.getNobleName())) return false;
      if (getIsNobleGift()
          != other.getIsNobleGift()) return false;
      if (getSeqNo()
          != other.getSeqNo()) return false;
      if (getHasGifPic()
          != other.getHasGifPic()) return false;
      if (getGiftType()
          != other.getGiftType()) return false;
      if (!getGifUrl()
          .equals(other.getGifUrl())) return false;
      if (getHasVggPic()
          != other.getHasVggPic()) return false;
      if (!getVggUrl()
          .equals(other.getVggUrl())) return false;
      if (getHasLatest()
          != other.getHasLatest()) return false;
      if (getHasTimeLimit()
          != other.getHasTimeLimit()) return false;
      if (getHasEffect()
          != other.getHasEffect()) return false;
      if (getHasCp()
          != other.getHasCp()) return false;
      if (getIsWholeServer()
          != other.getIsWholeServer()) return false;
      if (getIsSkipRoom()
          != other.getIsSkipRoom()) return false;
      if (getIsSendMsg()
          != other.getIsSendMsg()) return false;
      if (getConsumeType()
          != other.getConsumeType()) return false;
      if (getGiftIsSound()
          != other.getGiftIsSound()) return false;
      if (getGiftAvatarShowType()
          != other.getGiftAvatarShowType()) return false;
      if (!getUserInfoList()
          .equals(other.getUserInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GIFTID_FIELD_NUMBER;
      hash = (53 * hash) + getGiftId();
      hash = (37 * hash) + GIFTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGiftName().hashCode();
      hash = (37 * hash) + GOLDPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getGoldPrice()));
      hash = (37 * hash) + GIFTURL_FIELD_NUMBER;
      hash = (53 * hash) + getGiftUrl().hashCode();
      hash = (37 * hash) + NOBLEID_FIELD_NUMBER;
      hash = (53 * hash) + getNobleId();
      hash = (37 * hash) + NOBLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getNobleName().hashCode();
      hash = (37 * hash) + ISNOBLEGIFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNobleGift());
      hash = (37 * hash) + SEQNO_FIELD_NUMBER;
      hash = (53 * hash) + getSeqNo();
      hash = (37 * hash) + HASGIFPIC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasGifPic());
      hash = (37 * hash) + GIFTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getGiftType();
      hash = (37 * hash) + GIFURL_FIELD_NUMBER;
      hash = (53 * hash) + getGifUrl().hashCode();
      hash = (37 * hash) + HASVGGPIC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasVggPic());
      hash = (37 * hash) + VGGURL_FIELD_NUMBER;
      hash = (53 * hash) + getVggUrl().hashCode();
      hash = (37 * hash) + HASLATEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasLatest());
      hash = (37 * hash) + HASTIMELIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasTimeLimit());
      hash = (37 * hash) + HASEFFECT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasEffect());
      hash = (37 * hash) + HASCP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasCp());
      hash = (37 * hash) + ISWHOLESERVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsWholeServer());
      hash = (37 * hash) + ISSKIPROOM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSkipRoom());
      hash = (37 * hash) + ISSENDMSG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSendMsg());
      hash = (37 * hash) + CONSUMETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getConsumeType();
      hash = (37 * hash) + GIFTISSOUND_FIELD_NUMBER;
      hash = (53 * hash) + getGiftIsSound();
      hash = (37 * hash) + GIFTAVATARSHOWTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getGiftAvatarShowType();
      if (getUserInfoCount() > 0) {
        hash = (37 * hash) + USERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbGift.GiftVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.erban.main.proto.PbGift.GiftVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code allo.proto.GiftVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:allo.proto.GiftVo)
        com.erban.main.proto.PbGift.GiftVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.erban.main.proto.PbGift.internal_static_allo_proto_GiftVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.erban.main.proto.PbGift.internal_static_allo_proto_GiftVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.erban.main.proto.PbGift.GiftVo.class, com.erban.main.proto.PbGift.GiftVo.Builder.class);
      }

      // Construct using com.erban.main.proto.PbGift.GiftVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        giftId_ = 0;

        giftName_ = "";

        goldPrice_ = 0D;

        giftUrl_ = "";

        nobleId_ = 0;

        nobleName_ = "";

        isNobleGift_ = false;

        seqNo_ = 0;

        hasGifPic_ = false;

        giftType_ = 0;

        gifUrl_ = "";

        hasVggPic_ = false;

        vggUrl_ = "";

        hasLatest_ = false;

        hasTimeLimit_ = false;

        hasEffect_ = false;

        hasCp_ = false;

        isWholeServer_ = false;

        isSkipRoom_ = false;

        isSendMsg_ = false;

        consumeType_ = 0;

        giftIsSound_ = 0;

        giftAvatarShowType_ = 0;

        if (userInfoBuilder_ == null) {
          userInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00800000);
        } else {
          userInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.erban.main.proto.PbGift.internal_static_allo_proto_GiftVo_descriptor;
      }

      @java.lang.Override
      public com.erban.main.proto.PbGift.GiftVo getDefaultInstanceForType() {
        return com.erban.main.proto.PbGift.GiftVo.getDefaultInstance();
      }

      @java.lang.Override
      public com.erban.main.proto.PbGift.GiftVo build() {
        com.erban.main.proto.PbGift.GiftVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.erban.main.proto.PbGift.GiftVo buildPartial() {
        com.erban.main.proto.PbGift.GiftVo result = new com.erban.main.proto.PbGift.GiftVo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.giftId_ = giftId_;
        result.giftName_ = giftName_;
        result.goldPrice_ = goldPrice_;
        result.giftUrl_ = giftUrl_;
        result.nobleId_ = nobleId_;
        result.nobleName_ = nobleName_;
        result.isNobleGift_ = isNobleGift_;
        result.seqNo_ = seqNo_;
        result.hasGifPic_ = hasGifPic_;
        result.giftType_ = giftType_;
        result.gifUrl_ = gifUrl_;
        result.hasVggPic_ = hasVggPic_;
        result.vggUrl_ = vggUrl_;
        result.hasLatest_ = hasLatest_;
        result.hasTimeLimit_ = hasTimeLimit_;
        result.hasEffect_ = hasEffect_;
        result.hasCp_ = hasCp_;
        result.isWholeServer_ = isWholeServer_;
        result.isSkipRoom_ = isSkipRoom_;
        result.isSendMsg_ = isSendMsg_;
        result.consumeType_ = consumeType_;
        result.giftIsSound_ = giftIsSound_;
        result.giftAvatarShowType_ = giftAvatarShowType_;
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00800000) != 0)) {
            userInfo_ = java.util.Collections.unmodifiableList(userInfo_);
            bitField0_ = (bitField0_ & ~0x00800000);
          }
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.erban.main.proto.PbGift.GiftVo) {
          return mergeFrom((com.erban.main.proto.PbGift.GiftVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.erban.main.proto.PbGift.GiftVo other) {
        if (other == com.erban.main.proto.PbGift.GiftVo.getDefaultInstance()) return this;
        if (other.getGiftId() != 0) {
          setGiftId(other.getGiftId());
        }
        if (!other.getGiftName().isEmpty()) {
          giftName_ = other.giftName_;
          onChanged();
        }
        if (other.getGoldPrice() != 0D) {
          setGoldPrice(other.getGoldPrice());
        }
        if (!other.getGiftUrl().isEmpty()) {
          giftUrl_ = other.giftUrl_;
          onChanged();
        }
        if (other.getNobleId() != 0) {
          setNobleId(other.getNobleId());
        }
        if (!other.getNobleName().isEmpty()) {
          nobleName_ = other.nobleName_;
          onChanged();
        }
        if (other.getIsNobleGift() != false) {
          setIsNobleGift(other.getIsNobleGift());
        }
        if (other.getSeqNo() != 0) {
          setSeqNo(other.getSeqNo());
        }
        if (other.getHasGifPic() != false) {
          setHasGifPic(other.getHasGifPic());
        }
        if (other.getGiftType() != 0) {
          setGiftType(other.getGiftType());
        }
        if (!other.getGifUrl().isEmpty()) {
          gifUrl_ = other.gifUrl_;
          onChanged();
        }
        if (other.getHasVggPic() != false) {
          setHasVggPic(other.getHasVggPic());
        }
        if (!other.getVggUrl().isEmpty()) {
          vggUrl_ = other.vggUrl_;
          onChanged();
        }
        if (other.getHasLatest() != false) {
          setHasLatest(other.getHasLatest());
        }
        if (other.getHasTimeLimit() != false) {
          setHasTimeLimit(other.getHasTimeLimit());
        }
        if (other.getHasEffect() != false) {
          setHasEffect(other.getHasEffect());
        }
        if (other.getHasCp() != false) {
          setHasCp(other.getHasCp());
        }
        if (other.getIsWholeServer() != false) {
          setIsWholeServer(other.getIsWholeServer());
        }
        if (other.getIsSkipRoom() != false) {
          setIsSkipRoom(other.getIsSkipRoom());
        }
        if (other.getIsSendMsg() != false) {
          setIsSendMsg(other.getIsSendMsg());
        }
        if (other.getConsumeType() != 0) {
          setConsumeType(other.getConsumeType());
        }
        if (other.getGiftIsSound() != 0) {
          setGiftIsSound(other.getGiftIsSound());
        }
        if (other.getGiftAvatarShowType() != 0) {
          setGiftAvatarShowType(other.getGiftAvatarShowType());
        }
        if (userInfoBuilder_ == null) {
          if (!other.userInfo_.isEmpty()) {
            if (userInfo_.isEmpty()) {
              userInfo_ = other.userInfo_;
              bitField0_ = (bitField0_ & ~0x00800000);
            } else {
              ensureUserInfoIsMutable();
              userInfo_.addAll(other.userInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.userInfo_.isEmpty()) {
            if (userInfoBuilder_.isEmpty()) {
              userInfoBuilder_.dispose();
              userInfoBuilder_ = null;
              userInfo_ = other.userInfo_;
              bitField0_ = (bitField0_ & ~0x00800000);
              userInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserInfoFieldBuilder() : null;
            } else {
              userInfoBuilder_.addAllMessages(other.userInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.erban.main.proto.PbGift.GiftVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.erban.main.proto.PbGift.GiftVo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int giftId_ ;
      /**
       * <code>int32 giftId = 1;</code>
       */
      public int getGiftId() {
        return giftId_;
      }
      /**
       * <code>int32 giftId = 1;</code>
       */
      public Builder setGiftId(int value) {
        
        giftId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 giftId = 1;</code>
       */
      public Builder clearGiftId() {
        
        giftId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object giftName_ = "";
      /**
       * <code>string giftName = 2;</code>
       */
      public java.lang.String getGiftName() {
        java.lang.Object ref = giftName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          giftName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string giftName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGiftNameBytes() {
        java.lang.Object ref = giftName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          giftName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string giftName = 2;</code>
       */
      public Builder setGiftName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        giftName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string giftName = 2;</code>
       */
      public Builder clearGiftName() {
        
        giftName_ = getDefaultInstance().getGiftName();
        onChanged();
        return this;
      }
      /**
       * <code>string giftName = 2;</code>
       */
      public Builder setGiftNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        giftName_ = value;
        onChanged();
        return this;
      }

      private double goldPrice_ ;
      /**
       * <code>double goldPrice = 3;</code>
       */
      public double getGoldPrice() {
        return goldPrice_;
      }
      /**
       * <code>double goldPrice = 3;</code>
       */
      public Builder setGoldPrice(double value) {
        
        goldPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double goldPrice = 3;</code>
       */
      public Builder clearGoldPrice() {
        
        goldPrice_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object giftUrl_ = "";
      /**
       * <code>string giftUrl = 4;</code>
       */
      public java.lang.String getGiftUrl() {
        java.lang.Object ref = giftUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          giftUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string giftUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGiftUrlBytes() {
        java.lang.Object ref = giftUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          giftUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string giftUrl = 4;</code>
       */
      public Builder setGiftUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        giftUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string giftUrl = 4;</code>
       */
      public Builder clearGiftUrl() {
        
        giftUrl_ = getDefaultInstance().getGiftUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string giftUrl = 4;</code>
       */
      public Builder setGiftUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        giftUrl_ = value;
        onChanged();
        return this;
      }

      private int nobleId_ ;
      /**
       * <code>int32 nobleId = 5;</code>
       */
      public int getNobleId() {
        return nobleId_;
      }
      /**
       * <code>int32 nobleId = 5;</code>
       */
      public Builder setNobleId(int value) {
        
        nobleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nobleId = 5;</code>
       */
      public Builder clearNobleId() {
        
        nobleId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nobleName_ = "";
      /**
       * <code>string nobleName = 6;</code>
       */
      public java.lang.String getNobleName() {
        java.lang.Object ref = nobleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nobleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nobleName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNobleNameBytes() {
        java.lang.Object ref = nobleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nobleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nobleName = 6;</code>
       */
      public Builder setNobleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nobleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nobleName = 6;</code>
       */
      public Builder clearNobleName() {
        
        nobleName_ = getDefaultInstance().getNobleName();
        onChanged();
        return this;
      }
      /**
       * <code>string nobleName = 6;</code>
       */
      public Builder setNobleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nobleName_ = value;
        onChanged();
        return this;
      }

      private boolean isNobleGift_ ;
      /**
       * <code>bool isNobleGift = 7;</code>
       */
      public boolean getIsNobleGift() {
        return isNobleGift_;
      }
      /**
       * <code>bool isNobleGift = 7;</code>
       */
      public Builder setIsNobleGift(boolean value) {
        
        isNobleGift_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isNobleGift = 7;</code>
       */
      public Builder clearIsNobleGift() {
        
        isNobleGift_ = false;
        onChanged();
        return this;
      }

      private int seqNo_ ;
      /**
       * <code>int32 seqNo = 8;</code>
       */
      public int getSeqNo() {
        return seqNo_;
      }
      /**
       * <code>int32 seqNo = 8;</code>
       */
      public Builder setSeqNo(int value) {
        
        seqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seqNo = 8;</code>
       */
      public Builder clearSeqNo() {
        
        seqNo_ = 0;
        onChanged();
        return this;
      }

      private boolean hasGifPic_ ;
      /**
       * <code>bool hasGifPic = 9;</code>
       */
      public boolean getHasGifPic() {
        return hasGifPic_;
      }
      /**
       * <code>bool hasGifPic = 9;</code>
       */
      public Builder setHasGifPic(boolean value) {
        
        hasGifPic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hasGifPic = 9;</code>
       */
      public Builder clearHasGifPic() {
        
        hasGifPic_ = false;
        onChanged();
        return this;
      }

      private int giftType_ ;
      /**
       * <code>int32 giftType = 10;</code>
       */
      public int getGiftType() {
        return giftType_;
      }
      /**
       * <code>int32 giftType = 10;</code>
       */
      public Builder setGiftType(int value) {
        
        giftType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 giftType = 10;</code>
       */
      public Builder clearGiftType() {
        
        giftType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object gifUrl_ = "";
      /**
       * <code>string gifUrl = 11;</code>
       */
      public java.lang.String getGifUrl() {
        java.lang.Object ref = gifUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gifUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gifUrl = 11;</code>
       */
      public com.google.protobuf.ByteString
          getGifUrlBytes() {
        java.lang.Object ref = gifUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gifUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gifUrl = 11;</code>
       */
      public Builder setGifUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gifUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gifUrl = 11;</code>
       */
      public Builder clearGifUrl() {
        
        gifUrl_ = getDefaultInstance().getGifUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string gifUrl = 11;</code>
       */
      public Builder setGifUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gifUrl_ = value;
        onChanged();
        return this;
      }

      private boolean hasVggPic_ ;
      /**
       * <pre>
       *是否有vgg动画
       * </pre>
       *
       * <code>bool hasVggPic = 12;</code>
       */
      public boolean getHasVggPic() {
        return hasVggPic_;
      }
      /**
       * <pre>
       *是否有vgg动画
       * </pre>
       *
       * <code>bool hasVggPic = 12;</code>
       */
      public Builder setHasVggPic(boolean value) {
        
        hasVggPic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否有vgg动画
       * </pre>
       *
       * <code>bool hasVggPic = 12;</code>
       */
      public Builder clearHasVggPic() {
        
        hasVggPic_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object vggUrl_ = "";
      /**
       * <pre>
       *vgg动画链接
       * </pre>
       *
       * <code>string vggUrl = 13;</code>
       */
      public java.lang.String getVggUrl() {
        java.lang.Object ref = vggUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vggUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *vgg动画链接
       * </pre>
       *
       * <code>string vggUrl = 13;</code>
       */
      public com.google.protobuf.ByteString
          getVggUrlBytes() {
        java.lang.Object ref = vggUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vggUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *vgg动画链接
       * </pre>
       *
       * <code>string vggUrl = 13;</code>
       */
      public Builder setVggUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vggUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *vgg动画链接
       * </pre>
       *
       * <code>string vggUrl = 13;</code>
       */
      public Builder clearVggUrl() {
        
        vggUrl_ = getDefaultInstance().getVggUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *vgg动画链接
       * </pre>
       *
       * <code>string vggUrl = 13;</code>
       */
      public Builder setVggUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vggUrl_ = value;
        onChanged();
        return this;
      }

      private boolean hasLatest_ ;
      /**
       * <pre>
       *是否是最新礼物
       * </pre>
       *
       * <code>bool hasLatest = 14;</code>
       */
      public boolean getHasLatest() {
        return hasLatest_;
      }
      /**
       * <pre>
       *是否是最新礼物
       * </pre>
       *
       * <code>bool hasLatest = 14;</code>
       */
      public Builder setHasLatest(boolean value) {
        
        hasLatest_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否是最新礼物
       * </pre>
       *
       * <code>bool hasLatest = 14;</code>
       */
      public Builder clearHasLatest() {
        
        hasLatest_ = false;
        onChanged();
        return this;
      }

      private boolean hasTimeLimit_ ;
      /**
       * <pre>
       *是否是限时礼物
       * </pre>
       *
       * <code>bool hasTimeLimit = 15;</code>
       */
      public boolean getHasTimeLimit() {
        return hasTimeLimit_;
      }
      /**
       * <pre>
       *是否是限时礼物
       * </pre>
       *
       * <code>bool hasTimeLimit = 15;</code>
       */
      public Builder setHasTimeLimit(boolean value) {
        
        hasTimeLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否是限时礼物
       * </pre>
       *
       * <code>bool hasTimeLimit = 15;</code>
       */
      public Builder clearHasTimeLimit() {
        
        hasTimeLimit_ = false;
        onChanged();
        return this;
      }

      private boolean hasEffect_ ;
      /**
       * <pre>
       *是否有特效
       * </pre>
       *
       * <code>bool hasEffect = 16;</code>
       */
      public boolean getHasEffect() {
        return hasEffect_;
      }
      /**
       * <pre>
       *是否有特效
       * </pre>
       *
       * <code>bool hasEffect = 16;</code>
       */
      public Builder setHasEffect(boolean value) {
        
        hasEffect_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否有特效
       * </pre>
       *
       * <code>bool hasEffect = 16;</code>
       */
      public Builder clearHasEffect() {
        
        hasEffect_ = false;
        onChanged();
        return this;
      }

      private boolean hasCp_ ;
      /**
       * <pre>
       ** 是否CP礼物 
       * </pre>
       *
       * <code>bool hasCp = 17;</code>
       */
      public boolean getHasCp() {
        return hasCp_;
      }
      /**
       * <pre>
       ** 是否CP礼物 
       * </pre>
       *
       * <code>bool hasCp = 17;</code>
       */
      public Builder setHasCp(boolean value) {
        
        hasCp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 是否CP礼物 
       * </pre>
       *
       * <code>bool hasCp = 17;</code>
       */
      public Builder clearHasCp() {
        
        hasCp_ = false;
        onChanged();
        return this;
      }

      private boolean isWholeServer_ ;
      /**
       * <pre>
       *是否全服通知
       * </pre>
       *
       * <code>bool isWholeServer = 18;</code>
       */
      public boolean getIsWholeServer() {
        return isWholeServer_;
      }
      /**
       * <pre>
       *是否全服通知
       * </pre>
       *
       * <code>bool isWholeServer = 18;</code>
       */
      public Builder setIsWholeServer(boolean value) {
        
        isWholeServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否全服通知
       * </pre>
       *
       * <code>bool isWholeServer = 18;</code>
       */
      public Builder clearIsWholeServer() {
        
        isWholeServer_ = false;
        onChanged();
        return this;
      }

      private boolean isSkipRoom_ ;
      /**
       * <pre>
       * 全服通知是否支持房间跳转
       * </pre>
       *
       * <code>bool isSkipRoom = 19;</code>
       */
      public boolean getIsSkipRoom() {
        return isSkipRoom_;
      }
      /**
       * <pre>
       * 全服通知是否支持房间跳转
       * </pre>
       *
       * <code>bool isSkipRoom = 19;</code>
       */
      public Builder setIsSkipRoom(boolean value) {
        
        isSkipRoom_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 全服通知是否支持房间跳转
       * </pre>
       *
       * <code>bool isSkipRoom = 19;</code>
       */
      public Builder clearIsSkipRoom() {
        
        isSkipRoom_ = false;
        onChanged();
        return this;
      }

      private boolean isSendMsg_ ;
      /**
       * <pre>
       * 全服通知是否支持文字编辑
       * </pre>
       *
       * <code>bool isSendMsg = 20;</code>
       */
      public boolean getIsSendMsg() {
        return isSendMsg_;
      }
      /**
       * <pre>
       * 全服通知是否支持文字编辑
       * </pre>
       *
       * <code>bool isSendMsg = 20;</code>
       */
      public Builder setIsSendMsg(boolean value) {
        
        isSendMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 全服通知是否支持文字编辑
       * </pre>
       *
       * <code>bool isSendMsg = 20;</code>
       */
      public Builder clearIsSendMsg() {
        
        isSendMsg_ = false;
        onChanged();
        return this;
      }

      private int consumeType_ ;
      /**
       * <pre>
       *消费类型，1：金币礼物，2：萝卜礼物
       * </pre>
       *
       * <code>int32 consumeType = 21;</code>
       */
      public int getConsumeType() {
        return consumeType_;
      }
      /**
       * <pre>
       *消费类型，1：金币礼物，2：萝卜礼物
       * </pre>
       *
       * <code>int32 consumeType = 21;</code>
       */
      public Builder setConsumeType(int value) {
        
        consumeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消费类型，1：金币礼物，2：萝卜礼物
       * </pre>
       *
       * <code>int32 consumeType = 21;</code>
       */
      public Builder clearConsumeType() {
        
        consumeType_ = 0;
        onChanged();
        return this;
      }

      private int giftIsSound_ ;
      /**
       * <code>int32 giftIsSound = 22;</code>
       */
      public int getGiftIsSound() {
        return giftIsSound_;
      }
      /**
       * <code>int32 giftIsSound = 22;</code>
       */
      public Builder setGiftIsSound(int value) {
        
        giftIsSound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 giftIsSound = 22;</code>
       */
      public Builder clearGiftIsSound() {
        
        giftIsSound_ = 0;
        onChanged();
        return this;
      }

      private int giftAvatarShowType_ ;
      /**
       * <pre>
       *0.无1.普通收送礼人头像2.冠名用户头像3.CP用户头像
       * </pre>
       *
       * <code>int32 giftAvatarShowType = 23;</code>
       */
      public int getGiftAvatarShowType() {
        return giftAvatarShowType_;
      }
      /**
       * <pre>
       *0.无1.普通收送礼人头像2.冠名用户头像3.CP用户头像
       * </pre>
       *
       * <code>int32 giftAvatarShowType = 23;</code>
       */
      public Builder setGiftAvatarShowType(int value) {
        
        giftAvatarShowType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0.无1.普通收送礼人头像2.冠名用户头像3.CP用户头像
       * </pre>
       *
       * <code>int32 giftAvatarShowType = 23;</code>
       */
      public Builder clearGiftAvatarShowType() {
        
        giftAvatarShowType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.erban.main.proto.PbUser.PbUsers> userInfo_ =
        java.util.Collections.emptyList();
      private void ensureUserInfoIsMutable() {
        if (!((bitField0_ & 0x00800000) != 0)) {
          userInfo_ = new java.util.ArrayList<com.erban.main.proto.PbUser.PbUsers>(userInfo_);
          bitField0_ |= 0x00800000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.erban.main.proto.PbUser.PbUsers, com.erban.main.proto.PbUser.PbUsers.Builder, com.erban.main.proto.PbUser.PbUsersOrBuilder> userInfoBuilder_;

      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public java.util.List<com.erban.main.proto.PbUser.PbUsers> getUserInfoList() {
        if (userInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userInfo_);
        } else {
          return userInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public int getUserInfoCount() {
        if (userInfoBuilder_ == null) {
          return userInfo_.size();
        } else {
          return userInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public com.erban.main.proto.PbUser.PbUsers getUserInfo(int index) {
        if (userInfoBuilder_ == null) {
          return userInfo_.get(index);
        } else {
          return userInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder setUserInfo(
          int index, com.erban.main.proto.PbUser.PbUsers value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.set(index, value);
          onChanged();
        } else {
          userInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder setUserInfo(
          int index, com.erban.main.proto.PbUser.PbUsers.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder addUserInfo(com.erban.main.proto.PbUser.PbUsers value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.add(value);
          onChanged();
        } else {
          userInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder addUserInfo(
          int index, com.erban.main.proto.PbUser.PbUsers value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfoIsMutable();
          userInfo_.add(index, value);
          onChanged();
        } else {
          userInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder addUserInfo(
          com.erban.main.proto.PbUser.PbUsers.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.add(builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder addUserInfo(
          int index, com.erban.main.proto.PbUser.PbUsers.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          userInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder addAllUserInfo(
          java.lang.Iterable<? extends com.erban.main.proto.PbUser.PbUsers> values) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userInfo_);
          onChanged();
        } else {
          userInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00800000);
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public Builder removeUserInfo(int index) {
        if (userInfoBuilder_ == null) {
          ensureUserInfoIsMutable();
          userInfo_.remove(index);
          onChanged();
        } else {
          userInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public com.erban.main.proto.PbUser.PbUsers.Builder getUserInfoBuilder(
          int index) {
        return getUserInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public com.erban.main.proto.PbUser.PbUsersOrBuilder getUserInfoOrBuilder(
          int index) {
        if (userInfoBuilder_ == null) {
          return userInfo_.get(index);  } else {
          return userInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public java.util.List<? extends com.erban.main.proto.PbUser.PbUsersOrBuilder> 
           getUserInfoOrBuilderList() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userInfo_);
        }
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public com.erban.main.proto.PbUser.PbUsers.Builder addUserInfoBuilder() {
        return getUserInfoFieldBuilder().addBuilder(
            com.erban.main.proto.PbUser.PbUsers.getDefaultInstance());
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public com.erban.main.proto.PbUser.PbUsers.Builder addUserInfoBuilder(
          int index) {
        return getUserInfoFieldBuilder().addBuilder(
            index, com.erban.main.proto.PbUser.PbUsers.getDefaultInstance());
      }
      /**
       * <code>repeated .allo.proto.PbUsers userInfo = 24;</code>
       */
      public java.util.List<com.erban.main.proto.PbUser.PbUsers.Builder> 
           getUserInfoBuilderList() {
        return getUserInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.erban.main.proto.PbUser.PbUsers, com.erban.main.proto.PbUser.PbUsers.Builder, com.erban.main.proto.PbUser.PbUsersOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.erban.main.proto.PbUser.PbUsers, com.erban.main.proto.PbUser.PbUsers.Builder, com.erban.main.proto.PbUser.PbUsersOrBuilder>(
                  userInfo_,
                  ((bitField0_ & 0x00800000) != 0),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:allo.proto.GiftVo)
    }

    // @@protoc_insertion_point(class_scope:allo.proto.GiftVo)
    private static final com.erban.main.proto.PbGift.GiftVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.erban.main.proto.PbGift.GiftVo();
    }

    public static com.erban.main.proto.PbGift.GiftVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GiftVo>
        PARSER = new com.google.protobuf.AbstractParser<GiftVo>() {
      @java.lang.Override
      public GiftVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GiftVo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GiftVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GiftVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.erban.main.proto.PbGift.GiftVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allo_proto_GiftVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allo_proto_GiftVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpb_gift.proto\022\nallo.proto\032\rpb_user.pro" +
      "to\"\344\003\n\006GiftVo\022\016\n\006giftId\030\001 \001(\005\022\020\n\010giftNam" +
      "e\030\002 \001(\t\022\021\n\tgoldPrice\030\003 \001(\001\022\017\n\007giftUrl\030\004 " +
      "\001(\t\022\017\n\007nobleId\030\005 \001(\005\022\021\n\tnobleName\030\006 \001(\t\022" +
      "\023\n\013isNobleGift\030\007 \001(\010\022\r\n\005seqNo\030\010 \001(\005\022\021\n\th" +
      "asGifPic\030\t \001(\010\022\020\n\010giftType\030\n \001(\005\022\016\n\006gifU" +
      "rl\030\013 \001(\t\022\021\n\thasVggPic\030\014 \001(\010\022\016\n\006vggUrl\030\r " +
      "\001(\t\022\021\n\thasLatest\030\016 \001(\010\022\024\n\014hasTimeLimit\030\017" +
      " \001(\010\022\021\n\thasEffect\030\020 \001(\010\022\r\n\005hasCp\030\021 \001(\010\022\025" +
      "\n\risWholeServer\030\022 \001(\010\022\022\n\nisSkipRoom\030\023 \001(" +
      "\010\022\021\n\tisSendMsg\030\024 \001(\010\022\023\n\013consumeType\030\025 \001(" +
      "\005\022\023\n\013giftIsSound\030\026 \001(\005\022\032\n\022giftAvatarShow" +
      "Type\030\027 \001(\005\022%\n\010userInfo\030\030 \003(\0132\023.allo.prot" +
      "o.PbUsersB\026\n\024com.erban.main.protob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.erban.main.proto.PbUser.getDescriptor(),
        }, assigner);
    internal_static_allo_proto_GiftVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_allo_proto_GiftVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allo_proto_GiftVo_descriptor,
        new java.lang.String[] { "GiftId", "GiftName", "GoldPrice", "GiftUrl", "NobleId", "NobleName", "IsNobleGift", "SeqNo", "HasGifPic", "GiftType", "GifUrl", "HasVggPic", "VggUrl", "HasLatest", "HasTimeLimit", "HasEffect", "HasCp", "IsWholeServer", "IsSkipRoom", "IsSendMsg", "ConsumeType", "GiftIsSound", "GiftAvatarShowType", "UserInfo", });
    com.erban.main.proto.PbUser.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
