// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_live.proto

package com.erban.main.proto;

public final class PbLive {
  private PbLive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbLiveTagInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:allo.proto.PbLiveTagInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool liveTag = 1;</code>
     */
    boolean getLiveTag();

    /**
     * <code>string liveSkillName = 2;</code>
     */
    java.lang.String getLiveSkillName();
    /**
     * <code>string liveSkillName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLiveSkillNameBytes();

    /**
     * <code>string skillTag = 3;</code>
     */
    java.lang.String getSkillTag();
    /**
     * <code>string skillTag = 3;</code>
     */
    com.google.protobuf.ByteString
        getSkillTagBytes();

    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    java.util.List<com.erban.main.proto.PbLive.PbLiveSkillItem> 
        getLiveSkillVoListList();
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    com.erban.main.proto.PbLive.PbLiveSkillItem getLiveSkillVoList(int index);
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    int getLiveSkillVoListCount();
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    java.util.List<? extends com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder> 
        getLiveSkillVoListOrBuilderList();
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder getLiveSkillVoListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code allo.proto.PbLiveTagInfo}
   */
  public  static final class PbLiveTagInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:allo.proto.PbLiveTagInfo)
      PbLiveTagInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbLiveTagInfo.newBuilder() to construct.
    private PbLiveTagInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbLiveTagInfo() {
      liveSkillName_ = "";
      skillTag_ = "";
      liveSkillVoList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbLiveTagInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              liveTag_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              liveSkillName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              skillTag_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                liveSkillVoList_ = new java.util.ArrayList<com.erban.main.proto.PbLive.PbLiveSkillItem>();
                mutable_bitField0_ |= 0x00000008;
              }
              liveSkillVoList_.add(
                  input.readMessage(com.erban.main.proto.PbLive.PbLiveSkillItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          liveSkillVoList_ = java.util.Collections.unmodifiableList(liveSkillVoList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveTagInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveTagInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erban.main.proto.PbLive.PbLiveTagInfo.class, com.erban.main.proto.PbLive.PbLiveTagInfo.Builder.class);
    }

    private int bitField0_;
    public static final int LIVETAG_FIELD_NUMBER = 1;
    private boolean liveTag_;
    /**
     * <code>bool liveTag = 1;</code>
     */
    public boolean getLiveTag() {
      return liveTag_;
    }

    public static final int LIVESKILLNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object liveSkillName_;
    /**
     * <code>string liveSkillName = 2;</code>
     */
    public java.lang.String getLiveSkillName() {
      java.lang.Object ref = liveSkillName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        liveSkillName_ = s;
        return s;
      }
    }
    /**
     * <code>string liveSkillName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLiveSkillNameBytes() {
      java.lang.Object ref = liveSkillName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        liveSkillName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLTAG_FIELD_NUMBER = 3;
    private volatile java.lang.Object skillTag_;
    /**
     * <code>string skillTag = 3;</code>
     */
    public java.lang.String getSkillTag() {
      java.lang.Object ref = skillTag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillTag_ = s;
        return s;
      }
    }
    /**
     * <code>string skillTag = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSkillTagBytes() {
      java.lang.Object ref = skillTag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIVESKILLVOLIST_FIELD_NUMBER = 4;
    private java.util.List<com.erban.main.proto.PbLive.PbLiveSkillItem> liveSkillVoList_;
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    public java.util.List<com.erban.main.proto.PbLive.PbLiveSkillItem> getLiveSkillVoListList() {
      return liveSkillVoList_;
    }
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    public java.util.List<? extends com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder> 
        getLiveSkillVoListOrBuilderList() {
      return liveSkillVoList_;
    }
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    public int getLiveSkillVoListCount() {
      return liveSkillVoList_.size();
    }
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    public com.erban.main.proto.PbLive.PbLiveSkillItem getLiveSkillVoList(int index) {
      return liveSkillVoList_.get(index);
    }
    /**
     * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
     */
    public com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder getLiveSkillVoListOrBuilder(
        int index) {
      return liveSkillVoList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (liveTag_ != false) {
        output.writeBool(1, liveTag_);
      }
      if (!getLiveSkillNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, liveSkillName_);
      }
      if (!getSkillTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, skillTag_);
      }
      for (int i = 0; i < liveSkillVoList_.size(); i++) {
        output.writeMessage(4, liveSkillVoList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (liveTag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, liveTag_);
      }
      if (!getLiveSkillNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, liveSkillName_);
      }
      if (!getSkillTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, skillTag_);
      }
      for (int i = 0; i < liveSkillVoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, liveSkillVoList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.erban.main.proto.PbLive.PbLiveTagInfo)) {
        return super.equals(obj);
      }
      com.erban.main.proto.PbLive.PbLiveTagInfo other = (com.erban.main.proto.PbLive.PbLiveTagInfo) obj;

      if (getLiveTag()
          != other.getLiveTag()) return false;
      if (!getLiveSkillName()
          .equals(other.getLiveSkillName())) return false;
      if (!getSkillTag()
          .equals(other.getSkillTag())) return false;
      if (!getLiveSkillVoListList()
          .equals(other.getLiveSkillVoListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIVETAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLiveTag());
      hash = (37 * hash) + LIVESKILLNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLiveSkillName().hashCode();
      hash = (37 * hash) + SKILLTAG_FIELD_NUMBER;
      hash = (53 * hash) + getSkillTag().hashCode();
      if (getLiveSkillVoListCount() > 0) {
        hash = (37 * hash) + LIVESKILLVOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getLiveSkillVoListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbLive.PbLiveTagInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.erban.main.proto.PbLive.PbLiveTagInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code allo.proto.PbLiveTagInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:allo.proto.PbLiveTagInfo)
        com.erban.main.proto.PbLive.PbLiveTagInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveTagInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveTagInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.erban.main.proto.PbLive.PbLiveTagInfo.class, com.erban.main.proto.PbLive.PbLiveTagInfo.Builder.class);
      }

      // Construct using com.erban.main.proto.PbLive.PbLiveTagInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLiveSkillVoListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        liveTag_ = false;

        liveSkillName_ = "";

        skillTag_ = "";

        if (liveSkillVoListBuilder_ == null) {
          liveSkillVoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          liveSkillVoListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveTagInfo_descriptor;
      }

      @java.lang.Override
      public com.erban.main.proto.PbLive.PbLiveTagInfo getDefaultInstanceForType() {
        return com.erban.main.proto.PbLive.PbLiveTagInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.erban.main.proto.PbLive.PbLiveTagInfo build() {
        com.erban.main.proto.PbLive.PbLiveTagInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.erban.main.proto.PbLive.PbLiveTagInfo buildPartial() {
        com.erban.main.proto.PbLive.PbLiveTagInfo result = new com.erban.main.proto.PbLive.PbLiveTagInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.liveTag_ = liveTag_;
        result.liveSkillName_ = liveSkillName_;
        result.skillTag_ = skillTag_;
        if (liveSkillVoListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            liveSkillVoList_ = java.util.Collections.unmodifiableList(liveSkillVoList_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.liveSkillVoList_ = liveSkillVoList_;
        } else {
          result.liveSkillVoList_ = liveSkillVoListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.erban.main.proto.PbLive.PbLiveTagInfo) {
          return mergeFrom((com.erban.main.proto.PbLive.PbLiveTagInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.erban.main.proto.PbLive.PbLiveTagInfo other) {
        if (other == com.erban.main.proto.PbLive.PbLiveTagInfo.getDefaultInstance()) return this;
        if (other.getLiveTag() != false) {
          setLiveTag(other.getLiveTag());
        }
        if (!other.getLiveSkillName().isEmpty()) {
          liveSkillName_ = other.liveSkillName_;
          onChanged();
        }
        if (!other.getSkillTag().isEmpty()) {
          skillTag_ = other.skillTag_;
          onChanged();
        }
        if (liveSkillVoListBuilder_ == null) {
          if (!other.liveSkillVoList_.isEmpty()) {
            if (liveSkillVoList_.isEmpty()) {
              liveSkillVoList_ = other.liveSkillVoList_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLiveSkillVoListIsMutable();
              liveSkillVoList_.addAll(other.liveSkillVoList_);
            }
            onChanged();
          }
        } else {
          if (!other.liveSkillVoList_.isEmpty()) {
            if (liveSkillVoListBuilder_.isEmpty()) {
              liveSkillVoListBuilder_.dispose();
              liveSkillVoListBuilder_ = null;
              liveSkillVoList_ = other.liveSkillVoList_;
              bitField0_ = (bitField0_ & ~0x00000008);
              liveSkillVoListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLiveSkillVoListFieldBuilder() : null;
            } else {
              liveSkillVoListBuilder_.addAllMessages(other.liveSkillVoList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.erban.main.proto.PbLive.PbLiveTagInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.erban.main.proto.PbLive.PbLiveTagInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean liveTag_ ;
      /**
       * <code>bool liveTag = 1;</code>
       */
      public boolean getLiveTag() {
        return liveTag_;
      }
      /**
       * <code>bool liveTag = 1;</code>
       */
      public Builder setLiveTag(boolean value) {
        
        liveTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool liveTag = 1;</code>
       */
      public Builder clearLiveTag() {
        
        liveTag_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object liveSkillName_ = "";
      /**
       * <code>string liveSkillName = 2;</code>
       */
      public java.lang.String getLiveSkillName() {
        java.lang.Object ref = liveSkillName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          liveSkillName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string liveSkillName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLiveSkillNameBytes() {
        java.lang.Object ref = liveSkillName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          liveSkillName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string liveSkillName = 2;</code>
       */
      public Builder setLiveSkillName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        liveSkillName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string liveSkillName = 2;</code>
       */
      public Builder clearLiveSkillName() {
        
        liveSkillName_ = getDefaultInstance().getLiveSkillName();
        onChanged();
        return this;
      }
      /**
       * <code>string liveSkillName = 2;</code>
       */
      public Builder setLiveSkillNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        liveSkillName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object skillTag_ = "";
      /**
       * <code>string skillTag = 3;</code>
       */
      public java.lang.String getSkillTag() {
        java.lang.Object ref = skillTag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillTag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string skillTag = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSkillTagBytes() {
        java.lang.Object ref = skillTag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillTag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string skillTag = 3;</code>
       */
      public Builder setSkillTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string skillTag = 3;</code>
       */
      public Builder clearSkillTag() {
        
        skillTag_ = getDefaultInstance().getSkillTag();
        onChanged();
        return this;
      }
      /**
       * <code>string skillTag = 3;</code>
       */
      public Builder setSkillTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillTag_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.erban.main.proto.PbLive.PbLiveSkillItem> liveSkillVoList_ =
        java.util.Collections.emptyList();
      private void ensureLiveSkillVoListIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          liveSkillVoList_ = new java.util.ArrayList<com.erban.main.proto.PbLive.PbLiveSkillItem>(liveSkillVoList_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.erban.main.proto.PbLive.PbLiveSkillItem, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder, com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder> liveSkillVoListBuilder_;

      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public java.util.List<com.erban.main.proto.PbLive.PbLiveSkillItem> getLiveSkillVoListList() {
        if (liveSkillVoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(liveSkillVoList_);
        } else {
          return liveSkillVoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public int getLiveSkillVoListCount() {
        if (liveSkillVoListBuilder_ == null) {
          return liveSkillVoList_.size();
        } else {
          return liveSkillVoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public com.erban.main.proto.PbLive.PbLiveSkillItem getLiveSkillVoList(int index) {
        if (liveSkillVoListBuilder_ == null) {
          return liveSkillVoList_.get(index);
        } else {
          return liveSkillVoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder setLiveSkillVoList(
          int index, com.erban.main.proto.PbLive.PbLiveSkillItem value) {
        if (liveSkillVoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.set(index, value);
          onChanged();
        } else {
          liveSkillVoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder setLiveSkillVoList(
          int index, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder builderForValue) {
        if (liveSkillVoListBuilder_ == null) {
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          liveSkillVoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder addLiveSkillVoList(com.erban.main.proto.PbLive.PbLiveSkillItem value) {
        if (liveSkillVoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.add(value);
          onChanged();
        } else {
          liveSkillVoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder addLiveSkillVoList(
          int index, com.erban.main.proto.PbLive.PbLiveSkillItem value) {
        if (liveSkillVoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.add(index, value);
          onChanged();
        } else {
          liveSkillVoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder addLiveSkillVoList(
          com.erban.main.proto.PbLive.PbLiveSkillItem.Builder builderForValue) {
        if (liveSkillVoListBuilder_ == null) {
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.add(builderForValue.build());
          onChanged();
        } else {
          liveSkillVoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder addLiveSkillVoList(
          int index, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder builderForValue) {
        if (liveSkillVoListBuilder_ == null) {
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          liveSkillVoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder addAllLiveSkillVoList(
          java.lang.Iterable<? extends com.erban.main.proto.PbLive.PbLiveSkillItem> values) {
        if (liveSkillVoListBuilder_ == null) {
          ensureLiveSkillVoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, liveSkillVoList_);
          onChanged();
        } else {
          liveSkillVoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder clearLiveSkillVoList() {
        if (liveSkillVoListBuilder_ == null) {
          liveSkillVoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          liveSkillVoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public Builder removeLiveSkillVoList(int index) {
        if (liveSkillVoListBuilder_ == null) {
          ensureLiveSkillVoListIsMutable();
          liveSkillVoList_.remove(index);
          onChanged();
        } else {
          liveSkillVoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public com.erban.main.proto.PbLive.PbLiveSkillItem.Builder getLiveSkillVoListBuilder(
          int index) {
        return getLiveSkillVoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder getLiveSkillVoListOrBuilder(
          int index) {
        if (liveSkillVoListBuilder_ == null) {
          return liveSkillVoList_.get(index);  } else {
          return liveSkillVoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public java.util.List<? extends com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder> 
           getLiveSkillVoListOrBuilderList() {
        if (liveSkillVoListBuilder_ != null) {
          return liveSkillVoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(liveSkillVoList_);
        }
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public com.erban.main.proto.PbLive.PbLiveSkillItem.Builder addLiveSkillVoListBuilder() {
        return getLiveSkillVoListFieldBuilder().addBuilder(
            com.erban.main.proto.PbLive.PbLiveSkillItem.getDefaultInstance());
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public com.erban.main.proto.PbLive.PbLiveSkillItem.Builder addLiveSkillVoListBuilder(
          int index) {
        return getLiveSkillVoListFieldBuilder().addBuilder(
            index, com.erban.main.proto.PbLive.PbLiveSkillItem.getDefaultInstance());
      }
      /**
       * <code>repeated .allo.proto.PbLiveSkillItem liveSkillVoList = 4;</code>
       */
      public java.util.List<com.erban.main.proto.PbLive.PbLiveSkillItem.Builder> 
           getLiveSkillVoListBuilderList() {
        return getLiveSkillVoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.erban.main.proto.PbLive.PbLiveSkillItem, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder, com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder> 
          getLiveSkillVoListFieldBuilder() {
        if (liveSkillVoListBuilder_ == null) {
          liveSkillVoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.erban.main.proto.PbLive.PbLiveSkillItem, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder, com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder>(
                  liveSkillVoList_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          liveSkillVoList_ = null;
        }
        return liveSkillVoListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:allo.proto.PbLiveTagInfo)
    }

    // @@protoc_insertion_point(class_scope:allo.proto.PbLiveTagInfo)
    private static final com.erban.main.proto.PbLive.PbLiveTagInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.erban.main.proto.PbLive.PbLiveTagInfo();
    }

    public static com.erban.main.proto.PbLive.PbLiveTagInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbLiveTagInfo>
        PARSER = new com.google.protobuf.AbstractParser<PbLiveTagInfo>() {
      @java.lang.Override
      public PbLiveTagInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbLiveTagInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbLiveTagInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbLiveTagInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.erban.main.proto.PbLive.PbLiveTagInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PbLiveSkillItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:allo.proto.PbLiveSkillItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>int64 liveId = 2;</code>
     */
    long getLiveId();

    /**
     * <code>string skillName = 3;</code>
     */
    java.lang.String getSkillName();
    /**
     * <code>string skillName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSkillNameBytes();

    /**
     * <code>string skillPicture = 4;</code>
     */
    java.lang.String getSkillPicture();
    /**
     * <code>string skillPicture = 4;</code>
     */
    com.google.protobuf.ByteString
        getSkillPictureBytes();

    /**
     * <code>string skillType = 5;</code>
     */
    java.lang.String getSkillType();
    /**
     * <code>string skillType = 5;</code>
     */
    com.google.protobuf.ByteString
        getSkillTypeBytes();

    /**
     * <pre>
     *技能状态 1--未认证 2--审核中 3--已认证
     * </pre>
     *
     * <code>int32 status = 6;</code>
     */
    int getStatus();

    /**
     * <pre>
     * 是否激活 0-未激活 1-已激活
     * </pre>
     *
     * <code>int32 valid = 7;</code>
     */
    int getValid();

    /**
     * <pre>
     *是否使用 0-未使用 | 1-使用
     * </pre>
     *
     * <code>int32 hasUse = 8;</code>
     */
    int getHasUse();
  }
  /**
   * Protobuf type {@code allo.proto.PbLiveSkillItem}
   */
  public  static final class PbLiveSkillItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:allo.proto.PbLiveSkillItem)
      PbLiveSkillItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbLiveSkillItem.newBuilder() to construct.
    private PbLiveSkillItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbLiveSkillItem() {
      skillName_ = "";
      skillPicture_ = "";
      skillType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbLiveSkillItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              liveId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              skillName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              skillPicture_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              skillType_ = s;
              break;
            }
            case 48: {

              status_ = input.readInt32();
              break;
            }
            case 56: {

              valid_ = input.readInt32();
              break;
            }
            case 64: {

              hasUse_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveSkillItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveSkillItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erban.main.proto.PbLive.PbLiveSkillItem.class, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int LIVEID_FIELD_NUMBER = 2;
    private long liveId_;
    /**
     * <code>int64 liveId = 2;</code>
     */
    public long getLiveId() {
      return liveId_;
    }

    public static final int SKILLNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object skillName_;
    /**
     * <code>string skillName = 3;</code>
     */
    public java.lang.String getSkillName() {
      java.lang.Object ref = skillName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillName_ = s;
        return s;
      }
    }
    /**
     * <code>string skillName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSkillNameBytes() {
      java.lang.Object ref = skillName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLPICTURE_FIELD_NUMBER = 4;
    private volatile java.lang.Object skillPicture_;
    /**
     * <code>string skillPicture = 4;</code>
     */
    public java.lang.String getSkillPicture() {
      java.lang.Object ref = skillPicture_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillPicture_ = s;
        return s;
      }
    }
    /**
     * <code>string skillPicture = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSkillPictureBytes() {
      java.lang.Object ref = skillPicture_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillPicture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLTYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object skillType_;
    /**
     * <code>string skillType = 5;</code>
     */
    public java.lang.String getSkillType() {
      java.lang.Object ref = skillType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillType_ = s;
        return s;
      }
    }
    /**
     * <code>string skillType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSkillTypeBytes() {
      java.lang.Object ref = skillType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <pre>
     *技能状态 1--未认证 2--审核中 3--已认证
     * </pre>
     *
     * <code>int32 status = 6;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int VALID_FIELD_NUMBER = 7;
    private int valid_;
    /**
     * <pre>
     * 是否激活 0-未激活 1-已激活
     * </pre>
     *
     * <code>int32 valid = 7;</code>
     */
    public int getValid() {
      return valid_;
    }

    public static final int HASUSE_FIELD_NUMBER = 8;
    private int hasUse_;
    /**
     * <pre>
     *是否使用 0-未使用 | 1-使用
     * </pre>
     *
     * <code>int32 hasUse = 8;</code>
     */
    public int getHasUse() {
      return hasUse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (liveId_ != 0L) {
        output.writeInt64(2, liveId_);
      }
      if (!getSkillNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, skillName_);
      }
      if (!getSkillPictureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, skillPicture_);
      }
      if (!getSkillTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, skillType_);
      }
      if (status_ != 0) {
        output.writeInt32(6, status_);
      }
      if (valid_ != 0) {
        output.writeInt32(7, valid_);
      }
      if (hasUse_ != 0) {
        output.writeInt32(8, hasUse_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (liveId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, liveId_);
      }
      if (!getSkillNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, skillName_);
      }
      if (!getSkillPictureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, skillPicture_);
      }
      if (!getSkillTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, skillType_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, status_);
      }
      if (valid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, valid_);
      }
      if (hasUse_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, hasUse_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.erban.main.proto.PbLive.PbLiveSkillItem)) {
        return super.equals(obj);
      }
      com.erban.main.proto.PbLive.PbLiveSkillItem other = (com.erban.main.proto.PbLive.PbLiveSkillItem) obj;

      if (getId()
          != other.getId()) return false;
      if (getLiveId()
          != other.getLiveId()) return false;
      if (!getSkillName()
          .equals(other.getSkillName())) return false;
      if (!getSkillPicture()
          .equals(other.getSkillPicture())) return false;
      if (!getSkillType()
          .equals(other.getSkillType())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (getValid()
          != other.getValid()) return false;
      if (getHasUse()
          != other.getHasUse()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + LIVEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLiveId());
      hash = (37 * hash) + SKILLNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSkillName().hashCode();
      hash = (37 * hash) + SKILLPICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSkillPicture().hashCode();
      hash = (37 * hash) + SKILLTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSkillType().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + VALID_FIELD_NUMBER;
      hash = (53 * hash) + getValid();
      hash = (37 * hash) + HASUSE_FIELD_NUMBER;
      hash = (53 * hash) + getHasUse();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbLive.PbLiveSkillItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.erban.main.proto.PbLive.PbLiveSkillItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code allo.proto.PbLiveSkillItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:allo.proto.PbLiveSkillItem)
        com.erban.main.proto.PbLive.PbLiveSkillItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveSkillItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveSkillItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.erban.main.proto.PbLive.PbLiveSkillItem.class, com.erban.main.proto.PbLive.PbLiveSkillItem.Builder.class);
      }

      // Construct using com.erban.main.proto.PbLive.PbLiveSkillItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        liveId_ = 0L;

        skillName_ = "";

        skillPicture_ = "";

        skillType_ = "";

        status_ = 0;

        valid_ = 0;

        hasUse_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.erban.main.proto.PbLive.internal_static_allo_proto_PbLiveSkillItem_descriptor;
      }

      @java.lang.Override
      public com.erban.main.proto.PbLive.PbLiveSkillItem getDefaultInstanceForType() {
        return com.erban.main.proto.PbLive.PbLiveSkillItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.erban.main.proto.PbLive.PbLiveSkillItem build() {
        com.erban.main.proto.PbLive.PbLiveSkillItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.erban.main.proto.PbLive.PbLiveSkillItem buildPartial() {
        com.erban.main.proto.PbLive.PbLiveSkillItem result = new com.erban.main.proto.PbLive.PbLiveSkillItem(this);
        result.id_ = id_;
        result.liveId_ = liveId_;
        result.skillName_ = skillName_;
        result.skillPicture_ = skillPicture_;
        result.skillType_ = skillType_;
        result.status_ = status_;
        result.valid_ = valid_;
        result.hasUse_ = hasUse_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.erban.main.proto.PbLive.PbLiveSkillItem) {
          return mergeFrom((com.erban.main.proto.PbLive.PbLiveSkillItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.erban.main.proto.PbLive.PbLiveSkillItem other) {
        if (other == com.erban.main.proto.PbLive.PbLiveSkillItem.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getLiveId() != 0L) {
          setLiveId(other.getLiveId());
        }
        if (!other.getSkillName().isEmpty()) {
          skillName_ = other.skillName_;
          onChanged();
        }
        if (!other.getSkillPicture().isEmpty()) {
          skillPicture_ = other.skillPicture_;
          onChanged();
        }
        if (!other.getSkillType().isEmpty()) {
          skillType_ = other.skillType_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getValid() != 0) {
          setValid(other.getValid());
        }
        if (other.getHasUse() != 0) {
          setHasUse(other.getHasUse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.erban.main.proto.PbLive.PbLiveSkillItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.erban.main.proto.PbLive.PbLiveSkillItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long liveId_ ;
      /**
       * <code>int64 liveId = 2;</code>
       */
      public long getLiveId() {
        return liveId_;
      }
      /**
       * <code>int64 liveId = 2;</code>
       */
      public Builder setLiveId(long value) {
        
        liveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 liveId = 2;</code>
       */
      public Builder clearLiveId() {
        
        liveId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object skillName_ = "";
      /**
       * <code>string skillName = 3;</code>
       */
      public java.lang.String getSkillName() {
        java.lang.Object ref = skillName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string skillName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSkillNameBytes() {
        java.lang.Object ref = skillName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string skillName = 3;</code>
       */
      public Builder setSkillName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string skillName = 3;</code>
       */
      public Builder clearSkillName() {
        
        skillName_ = getDefaultInstance().getSkillName();
        onChanged();
        return this;
      }
      /**
       * <code>string skillName = 3;</code>
       */
      public Builder setSkillNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object skillPicture_ = "";
      /**
       * <code>string skillPicture = 4;</code>
       */
      public java.lang.String getSkillPicture() {
        java.lang.Object ref = skillPicture_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillPicture_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string skillPicture = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSkillPictureBytes() {
        java.lang.Object ref = skillPicture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillPicture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string skillPicture = 4;</code>
       */
      public Builder setSkillPicture(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillPicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string skillPicture = 4;</code>
       */
      public Builder clearSkillPicture() {
        
        skillPicture_ = getDefaultInstance().getSkillPicture();
        onChanged();
        return this;
      }
      /**
       * <code>string skillPicture = 4;</code>
       */
      public Builder setSkillPictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillPicture_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object skillType_ = "";
      /**
       * <code>string skillType = 5;</code>
       */
      public java.lang.String getSkillType() {
        java.lang.Object ref = skillType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string skillType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSkillTypeBytes() {
        java.lang.Object ref = skillType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string skillType = 5;</code>
       */
      public Builder setSkillType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string skillType = 5;</code>
       */
      public Builder clearSkillType() {
        
        skillType_ = getDefaultInstance().getSkillType();
        onChanged();
        return this;
      }
      /**
       * <code>string skillType = 5;</code>
       */
      public Builder setSkillTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillType_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       *技能状态 1--未认证 2--审核中 3--已认证
       * </pre>
       *
       * <code>int32 status = 6;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       *技能状态 1--未认证 2--审核中 3--已认证
       * </pre>
       *
       * <code>int32 status = 6;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *技能状态 1--未认证 2--审核中 3--已认证
       * </pre>
       *
       * <code>int32 status = 6;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int valid_ ;
      /**
       * <pre>
       * 是否激活 0-未激活 1-已激活
       * </pre>
       *
       * <code>int32 valid = 7;</code>
       */
      public int getValid() {
        return valid_;
      }
      /**
       * <pre>
       * 是否激活 0-未激活 1-已激活
       * </pre>
       *
       * <code>int32 valid = 7;</code>
       */
      public Builder setValid(int value) {
        
        valid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否激活 0-未激活 1-已激活
       * </pre>
       *
       * <code>int32 valid = 7;</code>
       */
      public Builder clearValid() {
        
        valid_ = 0;
        onChanged();
        return this;
      }

      private int hasUse_ ;
      /**
       * <pre>
       *是否使用 0-未使用 | 1-使用
       * </pre>
       *
       * <code>int32 hasUse = 8;</code>
       */
      public int getHasUse() {
        return hasUse_;
      }
      /**
       * <pre>
       *是否使用 0-未使用 | 1-使用
       * </pre>
       *
       * <code>int32 hasUse = 8;</code>
       */
      public Builder setHasUse(int value) {
        
        hasUse_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否使用 0-未使用 | 1-使用
       * </pre>
       *
       * <code>int32 hasUse = 8;</code>
       */
      public Builder clearHasUse() {
        
        hasUse_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:allo.proto.PbLiveSkillItem)
    }

    // @@protoc_insertion_point(class_scope:allo.proto.PbLiveSkillItem)
    private static final com.erban.main.proto.PbLive.PbLiveSkillItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.erban.main.proto.PbLive.PbLiveSkillItem();
    }

    public static com.erban.main.proto.PbLive.PbLiveSkillItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbLiveSkillItem>
        PARSER = new com.google.protobuf.AbstractParser<PbLiveSkillItem>() {
      @java.lang.Override
      public PbLiveSkillItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbLiveSkillItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbLiveSkillItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbLiveSkillItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.erban.main.proto.PbLive.PbLiveSkillItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allo_proto_PbLiveTagInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allo_proto_PbLiveTagInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allo_proto_PbLiveSkillItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allo_proto_PbLiveSkillItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpb_live.proto\022\nallo.proto\"\177\n\rPbLiveTag" +
      "Info\022\017\n\007liveTag\030\001 \001(\010\022\025\n\rliveSkillName\030\002" +
      " \001(\t\022\020\n\010skillTag\030\003 \001(\t\0224\n\017liveSkillVoLis" +
      "t\030\004 \003(\0132\033.allo.proto.PbLiveSkillItem\"\230\001\n" +
      "\017PbLiveSkillItem\022\n\n\002id\030\001 \001(\003\022\016\n\006liveId\030\002" +
      " \001(\003\022\021\n\tskillName\030\003 \001(\t\022\024\n\014skillPicture\030" +
      "\004 \001(\t\022\021\n\tskillType\030\005 \001(\t\022\016\n\006status\030\006 \001(\005" +
      "\022\r\n\005valid\030\007 \001(\005\022\016\n\006hasUse\030\010 \001(\005B\026\n\024com.e" +
      "rban.main.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_allo_proto_PbLiveTagInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_allo_proto_PbLiveTagInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allo_proto_PbLiveTagInfo_descriptor,
        new java.lang.String[] { "LiveTag", "LiveSkillName", "SkillTag", "LiveSkillVoList", });
    internal_static_allo_proto_PbLiveSkillItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_allo_proto_PbLiveSkillItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allo_proto_PbLiveSkillItem_descriptor,
        new java.lang.String[] { "Id", "LiveId", "SkillName", "SkillPicture", "SkillType", "Status", "Valid", "HasUse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
