// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_room_members.proto

package com.erban.main.proto;

public final class PbRoomMembers {
  private PbRoomMembers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbRoomMemberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:allo.proto.PbRoomMember)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 memRecordId = 1;</code>
     */
    long getMemRecordId();

    /**
     * <code>int64 roomUid = 2;</code>
     */
    long getRoomUid();

    /**
     * <code>int64 memberUid = 3;</code>
     */
    long getMemberUid();

    /**
     * <code>int32 memberStatus = 4;</code>
     */
    int getMemberStatus();

    /**
     * <code>int32 memberRole = 5;</code>
     */
    int getMemberRole();

    /**
     * <code>int64 applyTime = 6;</code>
     */
    long getApplyTime();

    /**
     * <code>int64 joinTime = 7;</code>
     */
    long getJoinTime();

    /**
     * <code>int64 updateTime = 8;</code>
     */
    long getUpdateTime();

    /**
     * <code>int64 erbanNo = 9;</code>
     */
    long getErbanNo();

    /**
     * <code>string avatar = 10;</code>
     */
    java.lang.String getAvatar();
    /**
     * <code>string avatar = 10;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <code>string nick = 11;</code>
     */
    java.lang.String getNick();
    /**
     * <code>string nick = 11;</code>
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <code>int32 gender = 12;</code>
     */
    int getGender();

    /**
     * <pre>
     *生日
     * </pre>
     *
     * <code>int64 birth = 13;</code>
     */
    long getBirth();

    /**
     * <pre>
     *是否靓号
     * </pre>
     *
     * <code>bool hasPrettyErbanNo = 14;</code>
     */
    boolean getHasPrettyErbanNo();

    /**
     * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
     */
    boolean hasUserLevelVo();
    /**
     * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
     */
    com.erban.main.proto.PbUser.PbUserLevelVo getUserLevelVo();
    /**
     * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
     */
    com.erban.main.proto.PbUser.PbUserLevelVoOrBuilder getUserLevelVoOrBuilder();

    /**
     * <pre>
     *头饰信息
     * </pre>
     *
     * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
     */
    boolean hasUserHeadwear();
    /**
     * <pre>
     *头饰信息
     * </pre>
     *
     * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
     */
    com.erban.main.proto.PbUser.PbUserHeadwearVo getUserHeadwear();
    /**
     * <pre>
     *头饰信息
     * </pre>
     *
     * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
     */
    com.erban.main.proto.PbUser.PbUserHeadwearVoOrBuilder getUserHeadwearOrBuilder();

    /**
     * <pre>
     *贵族信息
     * </pre>
     *
     * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
     */
    boolean hasNobleUsers();
    /**
     * <pre>
     *贵族信息
     * </pre>
     *
     * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
     */
    com.erban.main.proto.PbNoble.PbNobleUser getNobleUsers();
    /**
     * <pre>
     *贵族信息
     * </pre>
     *
     * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
     */
    com.erban.main.proto.PbNoble.PbNobleUserOrBuilder getNobleUsersOrBuilder();

    /**
     * <pre>
     *未读的申请消息
     * </pre>
     *
     * <code>int32 unReadApply = 18;</code>
     */
    int getUnReadApply();

    /**
     * <pre>
     *发送的消息内容
     * </pre>
     *
     * <code>string msgContent = 19;</code>
     */
    java.lang.String getMsgContent();
    /**
     * <pre>
     *发送的消息内容
     * </pre>
     *
     * <code>string msgContent = 19;</code>
     */
    com.google.protobuf.ByteString
        getMsgContentBytes();

    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    java.util.List<com.erban.main.proto.PbUser.PbBadgeUserVo> 
        getBadgeUserVoList();
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    com.erban.main.proto.PbUser.PbBadgeUserVo getBadgeUserVo(int index);
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    int getBadgeUserVoCount();
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    java.util.List<? extends com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder> 
        getBadgeUserVoOrBuilderList();
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder getBadgeUserVoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code allo.proto.PbRoomMember}
   */
  public  static final class PbRoomMember extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:allo.proto.PbRoomMember)
      PbRoomMemberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbRoomMember.newBuilder() to construct.
    private PbRoomMember(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbRoomMember() {
      avatar_ = "";
      nick_ = "";
      msgContent_ = "";
      badgeUserVo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbRoomMember(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              memRecordId_ = input.readInt64();
              break;
            }
            case 16: {

              roomUid_ = input.readInt64();
              break;
            }
            case 24: {

              memberUid_ = input.readInt64();
              break;
            }
            case 32: {

              memberStatus_ = input.readInt32();
              break;
            }
            case 40: {

              memberRole_ = input.readInt32();
              break;
            }
            case 48: {

              applyTime_ = input.readInt64();
              break;
            }
            case 56: {

              joinTime_ = input.readInt64();
              break;
            }
            case 64: {

              updateTime_ = input.readInt64();
              break;
            }
            case 72: {

              erbanNo_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              nick_ = s;
              break;
            }
            case 96: {

              gender_ = input.readInt32();
              break;
            }
            case 104: {

              birth_ = input.readInt64();
              break;
            }
            case 112: {

              hasPrettyErbanNo_ = input.readBool();
              break;
            }
            case 122: {
              com.erban.main.proto.PbUser.PbUserLevelVo.Builder subBuilder = null;
              if (userLevelVo_ != null) {
                subBuilder = userLevelVo_.toBuilder();
              }
              userLevelVo_ = input.readMessage(com.erban.main.proto.PbUser.PbUserLevelVo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userLevelVo_);
                userLevelVo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 130: {
              com.erban.main.proto.PbUser.PbUserHeadwearVo.Builder subBuilder = null;
              if (userHeadwear_ != null) {
                subBuilder = userHeadwear_.toBuilder();
              }
              userHeadwear_ = input.readMessage(com.erban.main.proto.PbUser.PbUserHeadwearVo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userHeadwear_);
                userHeadwear_ = subBuilder.buildPartial();
              }

              break;
            }
            case 138: {
              com.erban.main.proto.PbNoble.PbNobleUser.Builder subBuilder = null;
              if (nobleUsers_ != null) {
                subBuilder = nobleUsers_.toBuilder();
              }
              nobleUsers_ = input.readMessage(com.erban.main.proto.PbNoble.PbNobleUser.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nobleUsers_);
                nobleUsers_ = subBuilder.buildPartial();
              }

              break;
            }
            case 144: {

              unReadApply_ = input.readInt32();
              break;
            }
            case 154: {
              java.lang.String s = input.readStringRequireUtf8();

              msgContent_ = s;
              break;
            }
            case 162: {
              if (!((mutable_bitField0_ & 0x00080000) != 0)) {
                badgeUserVo_ = new java.util.ArrayList<com.erban.main.proto.PbUser.PbBadgeUserVo>();
                mutable_bitField0_ |= 0x00080000;
              }
              badgeUserVo_.add(
                  input.readMessage(com.erban.main.proto.PbUser.PbBadgeUserVo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00080000) != 0)) {
          badgeUserVo_ = java.util.Collections.unmodifiableList(badgeUserVo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erban.main.proto.PbRoomMembers.internal_static_allo_proto_PbRoomMember_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erban.main.proto.PbRoomMembers.internal_static_allo_proto_PbRoomMember_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erban.main.proto.PbRoomMembers.PbRoomMember.class, com.erban.main.proto.PbRoomMembers.PbRoomMember.Builder.class);
    }

    private int bitField0_;
    public static final int MEMRECORDID_FIELD_NUMBER = 1;
    private long memRecordId_;
    /**
     * <code>int64 memRecordId = 1;</code>
     */
    public long getMemRecordId() {
      return memRecordId_;
    }

    public static final int ROOMUID_FIELD_NUMBER = 2;
    private long roomUid_;
    /**
     * <code>int64 roomUid = 2;</code>
     */
    public long getRoomUid() {
      return roomUid_;
    }

    public static final int MEMBERUID_FIELD_NUMBER = 3;
    private long memberUid_;
    /**
     * <code>int64 memberUid = 3;</code>
     */
    public long getMemberUid() {
      return memberUid_;
    }

    public static final int MEMBERSTATUS_FIELD_NUMBER = 4;
    private int memberStatus_;
    /**
     * <code>int32 memberStatus = 4;</code>
     */
    public int getMemberStatus() {
      return memberStatus_;
    }

    public static final int MEMBERROLE_FIELD_NUMBER = 5;
    private int memberRole_;
    /**
     * <code>int32 memberRole = 5;</code>
     */
    public int getMemberRole() {
      return memberRole_;
    }

    public static final int APPLYTIME_FIELD_NUMBER = 6;
    private long applyTime_;
    /**
     * <code>int64 applyTime = 6;</code>
     */
    public long getApplyTime() {
      return applyTime_;
    }

    public static final int JOINTIME_FIELD_NUMBER = 7;
    private long joinTime_;
    /**
     * <code>int64 joinTime = 7;</code>
     */
    public long getJoinTime() {
      return joinTime_;
    }

    public static final int UPDATETIME_FIELD_NUMBER = 8;
    private long updateTime_;
    /**
     * <code>int64 updateTime = 8;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    public static final int ERBANNO_FIELD_NUMBER = 9;
    private long erbanNo_;
    /**
     * <code>int64 erbanNo = 9;</code>
     */
    public long getErbanNo() {
      return erbanNo_;
    }

    public static final int AVATAR_FIELD_NUMBER = 10;
    private volatile java.lang.Object avatar_;
    /**
     * <code>string avatar = 10;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <code>string avatar = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICK_FIELD_NUMBER = 11;
    private volatile java.lang.Object nick_;
    /**
     * <code>string nick = 11;</code>
     */
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      }
    }
    /**
     * <code>string nick = 11;</code>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 12;
    private int gender_;
    /**
     * <code>int32 gender = 12;</code>
     */
    public int getGender() {
      return gender_;
    }

    public static final int BIRTH_FIELD_NUMBER = 13;
    private long birth_;
    /**
     * <pre>
     *生日
     * </pre>
     *
     * <code>int64 birth = 13;</code>
     */
    public long getBirth() {
      return birth_;
    }

    public static final int HASPRETTYERBANNO_FIELD_NUMBER = 14;
    private boolean hasPrettyErbanNo_;
    /**
     * <pre>
     *是否靓号
     * </pre>
     *
     * <code>bool hasPrettyErbanNo = 14;</code>
     */
    public boolean getHasPrettyErbanNo() {
      return hasPrettyErbanNo_;
    }

    public static final int USERLEVELVO_FIELD_NUMBER = 15;
    private com.erban.main.proto.PbUser.PbUserLevelVo userLevelVo_;
    /**
     * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
     */
    public boolean hasUserLevelVo() {
      return userLevelVo_ != null;
    }
    /**
     * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
     */
    public com.erban.main.proto.PbUser.PbUserLevelVo getUserLevelVo() {
      return userLevelVo_ == null ? com.erban.main.proto.PbUser.PbUserLevelVo.getDefaultInstance() : userLevelVo_;
    }
    /**
     * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
     */
    public com.erban.main.proto.PbUser.PbUserLevelVoOrBuilder getUserLevelVoOrBuilder() {
      return getUserLevelVo();
    }

    public static final int USERHEADWEAR_FIELD_NUMBER = 16;
    private com.erban.main.proto.PbUser.PbUserHeadwearVo userHeadwear_;
    /**
     * <pre>
     *头饰信息
     * </pre>
     *
     * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
     */
    public boolean hasUserHeadwear() {
      return userHeadwear_ != null;
    }
    /**
     * <pre>
     *头饰信息
     * </pre>
     *
     * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
     */
    public com.erban.main.proto.PbUser.PbUserHeadwearVo getUserHeadwear() {
      return userHeadwear_ == null ? com.erban.main.proto.PbUser.PbUserHeadwearVo.getDefaultInstance() : userHeadwear_;
    }
    /**
     * <pre>
     *头饰信息
     * </pre>
     *
     * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
     */
    public com.erban.main.proto.PbUser.PbUserHeadwearVoOrBuilder getUserHeadwearOrBuilder() {
      return getUserHeadwear();
    }

    public static final int NOBLEUSERS_FIELD_NUMBER = 17;
    private com.erban.main.proto.PbNoble.PbNobleUser nobleUsers_;
    /**
     * <pre>
     *贵族信息
     * </pre>
     *
     * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
     */
    public boolean hasNobleUsers() {
      return nobleUsers_ != null;
    }
    /**
     * <pre>
     *贵族信息
     * </pre>
     *
     * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
     */
    public com.erban.main.proto.PbNoble.PbNobleUser getNobleUsers() {
      return nobleUsers_ == null ? com.erban.main.proto.PbNoble.PbNobleUser.getDefaultInstance() : nobleUsers_;
    }
    /**
     * <pre>
     *贵族信息
     * </pre>
     *
     * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
     */
    public com.erban.main.proto.PbNoble.PbNobleUserOrBuilder getNobleUsersOrBuilder() {
      return getNobleUsers();
    }

    public static final int UNREADAPPLY_FIELD_NUMBER = 18;
    private int unReadApply_;
    /**
     * <pre>
     *未读的申请消息
     * </pre>
     *
     * <code>int32 unReadApply = 18;</code>
     */
    public int getUnReadApply() {
      return unReadApply_;
    }

    public static final int MSGCONTENT_FIELD_NUMBER = 19;
    private volatile java.lang.Object msgContent_;
    /**
     * <pre>
     *发送的消息内容
     * </pre>
     *
     * <code>string msgContent = 19;</code>
     */
    public java.lang.String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送的消息内容
     * </pre>
     *
     * <code>string msgContent = 19;</code>
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BADGEUSERVO_FIELD_NUMBER = 20;
    private java.util.List<com.erban.main.proto.PbUser.PbBadgeUserVo> badgeUserVo_;
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    public java.util.List<com.erban.main.proto.PbUser.PbBadgeUserVo> getBadgeUserVoList() {
      return badgeUserVo_;
    }
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    public java.util.List<? extends com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder> 
        getBadgeUserVoOrBuilderList() {
      return badgeUserVo_;
    }
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    public int getBadgeUserVoCount() {
      return badgeUserVo_.size();
    }
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    public com.erban.main.proto.PbUser.PbBadgeUserVo getBadgeUserVo(int index) {
      return badgeUserVo_.get(index);
    }
    /**
     * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
     */
    public com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder getBadgeUserVoOrBuilder(
        int index) {
      return badgeUserVo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (memRecordId_ != 0L) {
        output.writeInt64(1, memRecordId_);
      }
      if (roomUid_ != 0L) {
        output.writeInt64(2, roomUid_);
      }
      if (memberUid_ != 0L) {
        output.writeInt64(3, memberUid_);
      }
      if (memberStatus_ != 0) {
        output.writeInt32(4, memberStatus_);
      }
      if (memberRole_ != 0) {
        output.writeInt32(5, memberRole_);
      }
      if (applyTime_ != 0L) {
        output.writeInt64(6, applyTime_);
      }
      if (joinTime_ != 0L) {
        output.writeInt64(7, joinTime_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(8, updateTime_);
      }
      if (erbanNo_ != 0L) {
        output.writeInt64(9, erbanNo_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, avatar_);
      }
      if (!getNickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, nick_);
      }
      if (gender_ != 0) {
        output.writeInt32(12, gender_);
      }
      if (birth_ != 0L) {
        output.writeInt64(13, birth_);
      }
      if (hasPrettyErbanNo_ != false) {
        output.writeBool(14, hasPrettyErbanNo_);
      }
      if (userLevelVo_ != null) {
        output.writeMessage(15, getUserLevelVo());
      }
      if (userHeadwear_ != null) {
        output.writeMessage(16, getUserHeadwear());
      }
      if (nobleUsers_ != null) {
        output.writeMessage(17, getNobleUsers());
      }
      if (unReadApply_ != 0) {
        output.writeInt32(18, unReadApply_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, msgContent_);
      }
      for (int i = 0; i < badgeUserVo_.size(); i++) {
        output.writeMessage(20, badgeUserVo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (memRecordId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, memRecordId_);
      }
      if (roomUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, roomUid_);
      }
      if (memberUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, memberUid_);
      }
      if (memberStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, memberStatus_);
      }
      if (memberRole_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, memberRole_);
      }
      if (applyTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, applyTime_);
      }
      if (joinTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, joinTime_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, updateTime_);
      }
      if (erbanNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, erbanNo_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, avatar_);
      }
      if (!getNickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, nick_);
      }
      if (gender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, gender_);
      }
      if (birth_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, birth_);
      }
      if (hasPrettyErbanNo_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, hasPrettyErbanNo_);
      }
      if (userLevelVo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getUserLevelVo());
      }
      if (userHeadwear_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getUserHeadwear());
      }
      if (nobleUsers_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, getNobleUsers());
      }
      if (unReadApply_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, unReadApply_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, msgContent_);
      }
      for (int i = 0; i < badgeUserVo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, badgeUserVo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.erban.main.proto.PbRoomMembers.PbRoomMember)) {
        return super.equals(obj);
      }
      com.erban.main.proto.PbRoomMembers.PbRoomMember other = (com.erban.main.proto.PbRoomMembers.PbRoomMember) obj;

      if (getMemRecordId()
          != other.getMemRecordId()) return false;
      if (getRoomUid()
          != other.getRoomUid()) return false;
      if (getMemberUid()
          != other.getMemberUid()) return false;
      if (getMemberStatus()
          != other.getMemberStatus()) return false;
      if (getMemberRole()
          != other.getMemberRole()) return false;
      if (getApplyTime()
          != other.getApplyTime()) return false;
      if (getJoinTime()
          != other.getJoinTime()) return false;
      if (getUpdateTime()
          != other.getUpdateTime()) return false;
      if (getErbanNo()
          != other.getErbanNo()) return false;
      if (!getAvatar()
          .equals(other.getAvatar())) return false;
      if (!getNick()
          .equals(other.getNick())) return false;
      if (getGender()
          != other.getGender()) return false;
      if (getBirth()
          != other.getBirth()) return false;
      if (getHasPrettyErbanNo()
          != other.getHasPrettyErbanNo()) return false;
      if (hasUserLevelVo() != other.hasUserLevelVo()) return false;
      if (hasUserLevelVo()) {
        if (!getUserLevelVo()
            .equals(other.getUserLevelVo())) return false;
      }
      if (hasUserHeadwear() != other.hasUserHeadwear()) return false;
      if (hasUserHeadwear()) {
        if (!getUserHeadwear()
            .equals(other.getUserHeadwear())) return false;
      }
      if (hasNobleUsers() != other.hasNobleUsers()) return false;
      if (hasNobleUsers()) {
        if (!getNobleUsers()
            .equals(other.getNobleUsers())) return false;
      }
      if (getUnReadApply()
          != other.getUnReadApply()) return false;
      if (!getMsgContent()
          .equals(other.getMsgContent())) return false;
      if (!getBadgeUserVoList()
          .equals(other.getBadgeUserVoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEMRECORDID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemRecordId());
      hash = (37 * hash) + ROOMUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomUid());
      hash = (37 * hash) + MEMBERUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemberUid());
      hash = (37 * hash) + MEMBERSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getMemberStatus();
      hash = (37 * hash) + MEMBERROLE_FIELD_NUMBER;
      hash = (53 * hash) + getMemberRole();
      hash = (37 * hash) + APPLYTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getApplyTime());
      hash = (37 * hash) + JOINTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getJoinTime());
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (37 * hash) + ERBANNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getErbanNo());
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (37 * hash) + NICK_FIELD_NUMBER;
      hash = (53 * hash) + getNick().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender();
      hash = (37 * hash) + BIRTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBirth());
      hash = (37 * hash) + HASPRETTYERBANNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasPrettyErbanNo());
      if (hasUserLevelVo()) {
        hash = (37 * hash) + USERLEVELVO_FIELD_NUMBER;
        hash = (53 * hash) + getUserLevelVo().hashCode();
      }
      if (hasUserHeadwear()) {
        hash = (37 * hash) + USERHEADWEAR_FIELD_NUMBER;
        hash = (53 * hash) + getUserHeadwear().hashCode();
      }
      if (hasNobleUsers()) {
        hash = (37 * hash) + NOBLEUSERS_FIELD_NUMBER;
        hash = (53 * hash) + getNobleUsers().hashCode();
      }
      hash = (37 * hash) + UNREADAPPLY_FIELD_NUMBER;
      hash = (53 * hash) + getUnReadApply();
      hash = (37 * hash) + MSGCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMsgContent().hashCode();
      if (getBadgeUserVoCount() > 0) {
        hash = (37 * hash) + BADGEUSERVO_FIELD_NUMBER;
        hash = (53 * hash) + getBadgeUserVoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erban.main.proto.PbRoomMembers.PbRoomMember parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.erban.main.proto.PbRoomMembers.PbRoomMember prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code allo.proto.PbRoomMember}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:allo.proto.PbRoomMember)
        com.erban.main.proto.PbRoomMembers.PbRoomMemberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.erban.main.proto.PbRoomMembers.internal_static_allo_proto_PbRoomMember_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.erban.main.proto.PbRoomMembers.internal_static_allo_proto_PbRoomMember_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.erban.main.proto.PbRoomMembers.PbRoomMember.class, com.erban.main.proto.PbRoomMembers.PbRoomMember.Builder.class);
      }

      // Construct using com.erban.main.proto.PbRoomMembers.PbRoomMember.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBadgeUserVoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        memRecordId_ = 0L;

        roomUid_ = 0L;

        memberUid_ = 0L;

        memberStatus_ = 0;

        memberRole_ = 0;

        applyTime_ = 0L;

        joinTime_ = 0L;

        updateTime_ = 0L;

        erbanNo_ = 0L;

        avatar_ = "";

        nick_ = "";

        gender_ = 0;

        birth_ = 0L;

        hasPrettyErbanNo_ = false;

        if (userLevelVoBuilder_ == null) {
          userLevelVo_ = null;
        } else {
          userLevelVo_ = null;
          userLevelVoBuilder_ = null;
        }
        if (userHeadwearBuilder_ == null) {
          userHeadwear_ = null;
        } else {
          userHeadwear_ = null;
          userHeadwearBuilder_ = null;
        }
        if (nobleUsersBuilder_ == null) {
          nobleUsers_ = null;
        } else {
          nobleUsers_ = null;
          nobleUsersBuilder_ = null;
        }
        unReadApply_ = 0;

        msgContent_ = "";

        if (badgeUserVoBuilder_ == null) {
          badgeUserVo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00080000);
        } else {
          badgeUserVoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.erban.main.proto.PbRoomMembers.internal_static_allo_proto_PbRoomMember_descriptor;
      }

      @java.lang.Override
      public com.erban.main.proto.PbRoomMembers.PbRoomMember getDefaultInstanceForType() {
        return com.erban.main.proto.PbRoomMembers.PbRoomMember.getDefaultInstance();
      }

      @java.lang.Override
      public com.erban.main.proto.PbRoomMembers.PbRoomMember build() {
        com.erban.main.proto.PbRoomMembers.PbRoomMember result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.erban.main.proto.PbRoomMembers.PbRoomMember buildPartial() {
        com.erban.main.proto.PbRoomMembers.PbRoomMember result = new com.erban.main.proto.PbRoomMembers.PbRoomMember(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.memRecordId_ = memRecordId_;
        result.roomUid_ = roomUid_;
        result.memberUid_ = memberUid_;
        result.memberStatus_ = memberStatus_;
        result.memberRole_ = memberRole_;
        result.applyTime_ = applyTime_;
        result.joinTime_ = joinTime_;
        result.updateTime_ = updateTime_;
        result.erbanNo_ = erbanNo_;
        result.avatar_ = avatar_;
        result.nick_ = nick_;
        result.gender_ = gender_;
        result.birth_ = birth_;
        result.hasPrettyErbanNo_ = hasPrettyErbanNo_;
        if (userLevelVoBuilder_ == null) {
          result.userLevelVo_ = userLevelVo_;
        } else {
          result.userLevelVo_ = userLevelVoBuilder_.build();
        }
        if (userHeadwearBuilder_ == null) {
          result.userHeadwear_ = userHeadwear_;
        } else {
          result.userHeadwear_ = userHeadwearBuilder_.build();
        }
        if (nobleUsersBuilder_ == null) {
          result.nobleUsers_ = nobleUsers_;
        } else {
          result.nobleUsers_ = nobleUsersBuilder_.build();
        }
        result.unReadApply_ = unReadApply_;
        result.msgContent_ = msgContent_;
        if (badgeUserVoBuilder_ == null) {
          if (((bitField0_ & 0x00080000) != 0)) {
            badgeUserVo_ = java.util.Collections.unmodifiableList(badgeUserVo_);
            bitField0_ = (bitField0_ & ~0x00080000);
          }
          result.badgeUserVo_ = badgeUserVo_;
        } else {
          result.badgeUserVo_ = badgeUserVoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.erban.main.proto.PbRoomMembers.PbRoomMember) {
          return mergeFrom((com.erban.main.proto.PbRoomMembers.PbRoomMember)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.erban.main.proto.PbRoomMembers.PbRoomMember other) {
        if (other == com.erban.main.proto.PbRoomMembers.PbRoomMember.getDefaultInstance()) return this;
        if (other.getMemRecordId() != 0L) {
          setMemRecordId(other.getMemRecordId());
        }
        if (other.getRoomUid() != 0L) {
          setRoomUid(other.getRoomUid());
        }
        if (other.getMemberUid() != 0L) {
          setMemberUid(other.getMemberUid());
        }
        if (other.getMemberStatus() != 0) {
          setMemberStatus(other.getMemberStatus());
        }
        if (other.getMemberRole() != 0) {
          setMemberRole(other.getMemberRole());
        }
        if (other.getApplyTime() != 0L) {
          setApplyTime(other.getApplyTime());
        }
        if (other.getJoinTime() != 0L) {
          setJoinTime(other.getJoinTime());
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        if (other.getErbanNo() != 0L) {
          setErbanNo(other.getErbanNo());
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        if (!other.getNick().isEmpty()) {
          nick_ = other.nick_;
          onChanged();
        }
        if (other.getGender() != 0) {
          setGender(other.getGender());
        }
        if (other.getBirth() != 0L) {
          setBirth(other.getBirth());
        }
        if (other.getHasPrettyErbanNo() != false) {
          setHasPrettyErbanNo(other.getHasPrettyErbanNo());
        }
        if (other.hasUserLevelVo()) {
          mergeUserLevelVo(other.getUserLevelVo());
        }
        if (other.hasUserHeadwear()) {
          mergeUserHeadwear(other.getUserHeadwear());
        }
        if (other.hasNobleUsers()) {
          mergeNobleUsers(other.getNobleUsers());
        }
        if (other.getUnReadApply() != 0) {
          setUnReadApply(other.getUnReadApply());
        }
        if (!other.getMsgContent().isEmpty()) {
          msgContent_ = other.msgContent_;
          onChanged();
        }
        if (badgeUserVoBuilder_ == null) {
          if (!other.badgeUserVo_.isEmpty()) {
            if (badgeUserVo_.isEmpty()) {
              badgeUserVo_ = other.badgeUserVo_;
              bitField0_ = (bitField0_ & ~0x00080000);
            } else {
              ensureBadgeUserVoIsMutable();
              badgeUserVo_.addAll(other.badgeUserVo_);
            }
            onChanged();
          }
        } else {
          if (!other.badgeUserVo_.isEmpty()) {
            if (badgeUserVoBuilder_.isEmpty()) {
              badgeUserVoBuilder_.dispose();
              badgeUserVoBuilder_ = null;
              badgeUserVo_ = other.badgeUserVo_;
              bitField0_ = (bitField0_ & ~0x00080000);
              badgeUserVoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBadgeUserVoFieldBuilder() : null;
            } else {
              badgeUserVoBuilder_.addAllMessages(other.badgeUserVo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.erban.main.proto.PbRoomMembers.PbRoomMember parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.erban.main.proto.PbRoomMembers.PbRoomMember) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long memRecordId_ ;
      /**
       * <code>int64 memRecordId = 1;</code>
       */
      public long getMemRecordId() {
        return memRecordId_;
      }
      /**
       * <code>int64 memRecordId = 1;</code>
       */
      public Builder setMemRecordId(long value) {
        
        memRecordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 memRecordId = 1;</code>
       */
      public Builder clearMemRecordId() {
        
        memRecordId_ = 0L;
        onChanged();
        return this;
      }

      private long roomUid_ ;
      /**
       * <code>int64 roomUid = 2;</code>
       */
      public long getRoomUid() {
        return roomUid_;
      }
      /**
       * <code>int64 roomUid = 2;</code>
       */
      public Builder setRoomUid(long value) {
        
        roomUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 roomUid = 2;</code>
       */
      public Builder clearRoomUid() {
        
        roomUid_ = 0L;
        onChanged();
        return this;
      }

      private long memberUid_ ;
      /**
       * <code>int64 memberUid = 3;</code>
       */
      public long getMemberUid() {
        return memberUid_;
      }
      /**
       * <code>int64 memberUid = 3;</code>
       */
      public Builder setMemberUid(long value) {
        
        memberUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 memberUid = 3;</code>
       */
      public Builder clearMemberUid() {
        
        memberUid_ = 0L;
        onChanged();
        return this;
      }

      private int memberStatus_ ;
      /**
       * <code>int32 memberStatus = 4;</code>
       */
      public int getMemberStatus() {
        return memberStatus_;
      }
      /**
       * <code>int32 memberStatus = 4;</code>
       */
      public Builder setMemberStatus(int value) {
        
        memberStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memberStatus = 4;</code>
       */
      public Builder clearMemberStatus() {
        
        memberStatus_ = 0;
        onChanged();
        return this;
      }

      private int memberRole_ ;
      /**
       * <code>int32 memberRole = 5;</code>
       */
      public int getMemberRole() {
        return memberRole_;
      }
      /**
       * <code>int32 memberRole = 5;</code>
       */
      public Builder setMemberRole(int value) {
        
        memberRole_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memberRole = 5;</code>
       */
      public Builder clearMemberRole() {
        
        memberRole_ = 0;
        onChanged();
        return this;
      }

      private long applyTime_ ;
      /**
       * <code>int64 applyTime = 6;</code>
       */
      public long getApplyTime() {
        return applyTime_;
      }
      /**
       * <code>int64 applyTime = 6;</code>
       */
      public Builder setApplyTime(long value) {
        
        applyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 applyTime = 6;</code>
       */
      public Builder clearApplyTime() {
        
        applyTime_ = 0L;
        onChanged();
        return this;
      }

      private long joinTime_ ;
      /**
       * <code>int64 joinTime = 7;</code>
       */
      public long getJoinTime() {
        return joinTime_;
      }
      /**
       * <code>int64 joinTime = 7;</code>
       */
      public Builder setJoinTime(long value) {
        
        joinTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 joinTime = 7;</code>
       */
      public Builder clearJoinTime() {
        
        joinTime_ = 0L;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <code>int64 updateTime = 8;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>int64 updateTime = 8;</code>
       */
      public Builder setUpdateTime(long value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updateTime = 8;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0L;
        onChanged();
        return this;
      }

      private long erbanNo_ ;
      /**
       * <code>int64 erbanNo = 9;</code>
       */
      public long getErbanNo() {
        return erbanNo_;
      }
      /**
       * <code>int64 erbanNo = 9;</code>
       */
      public Builder setErbanNo(long value) {
        
        erbanNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 erbanNo = 9;</code>
       */
      public Builder clearErbanNo() {
        
        erbanNo_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <code>string avatar = 10;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avatar = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avatar = 10;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 10;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>string avatar = 10;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nick_ = "";
      /**
       * <code>string nick = 11;</code>
       */
      public java.lang.String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nick = 11;</code>
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        java.lang.Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nick = 11;</code>
       */
      public Builder setNick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 11;</code>
       */
      public Builder clearNick() {
        
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 11;</code>
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nick_ = value;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <code>int32 gender = 12;</code>
       */
      public int getGender() {
        return gender_;
      }
      /**
       * <code>int32 gender = 12;</code>
       */
      public Builder setGender(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 gender = 12;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private long birth_ ;
      /**
       * <pre>
       *生日
       * </pre>
       *
       * <code>int64 birth = 13;</code>
       */
      public long getBirth() {
        return birth_;
      }
      /**
       * <pre>
       *生日
       * </pre>
       *
       * <code>int64 birth = 13;</code>
       */
      public Builder setBirth(long value) {
        
        birth_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *生日
       * </pre>
       *
       * <code>int64 birth = 13;</code>
       */
      public Builder clearBirth() {
        
        birth_ = 0L;
        onChanged();
        return this;
      }

      private boolean hasPrettyErbanNo_ ;
      /**
       * <pre>
       *是否靓号
       * </pre>
       *
       * <code>bool hasPrettyErbanNo = 14;</code>
       */
      public boolean getHasPrettyErbanNo() {
        return hasPrettyErbanNo_;
      }
      /**
       * <pre>
       *是否靓号
       * </pre>
       *
       * <code>bool hasPrettyErbanNo = 14;</code>
       */
      public Builder setHasPrettyErbanNo(boolean value) {
        
        hasPrettyErbanNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否靓号
       * </pre>
       *
       * <code>bool hasPrettyErbanNo = 14;</code>
       */
      public Builder clearHasPrettyErbanNo() {
        
        hasPrettyErbanNo_ = false;
        onChanged();
        return this;
      }

      private com.erban.main.proto.PbUser.PbUserLevelVo userLevelVo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.erban.main.proto.PbUser.PbUserLevelVo, com.erban.main.proto.PbUser.PbUserLevelVo.Builder, com.erban.main.proto.PbUser.PbUserLevelVoOrBuilder> userLevelVoBuilder_;
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public boolean hasUserLevelVo() {
        return userLevelVoBuilder_ != null || userLevelVo_ != null;
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public com.erban.main.proto.PbUser.PbUserLevelVo getUserLevelVo() {
        if (userLevelVoBuilder_ == null) {
          return userLevelVo_ == null ? com.erban.main.proto.PbUser.PbUserLevelVo.getDefaultInstance() : userLevelVo_;
        } else {
          return userLevelVoBuilder_.getMessage();
        }
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public Builder setUserLevelVo(com.erban.main.proto.PbUser.PbUserLevelVo value) {
        if (userLevelVoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userLevelVo_ = value;
          onChanged();
        } else {
          userLevelVoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public Builder setUserLevelVo(
          com.erban.main.proto.PbUser.PbUserLevelVo.Builder builderForValue) {
        if (userLevelVoBuilder_ == null) {
          userLevelVo_ = builderForValue.build();
          onChanged();
        } else {
          userLevelVoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public Builder mergeUserLevelVo(com.erban.main.proto.PbUser.PbUserLevelVo value) {
        if (userLevelVoBuilder_ == null) {
          if (userLevelVo_ != null) {
            userLevelVo_ =
              com.erban.main.proto.PbUser.PbUserLevelVo.newBuilder(userLevelVo_).mergeFrom(value).buildPartial();
          } else {
            userLevelVo_ = value;
          }
          onChanged();
        } else {
          userLevelVoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public Builder clearUserLevelVo() {
        if (userLevelVoBuilder_ == null) {
          userLevelVo_ = null;
          onChanged();
        } else {
          userLevelVo_ = null;
          userLevelVoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public com.erban.main.proto.PbUser.PbUserLevelVo.Builder getUserLevelVoBuilder() {
        
        onChanged();
        return getUserLevelVoFieldBuilder().getBuilder();
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      public com.erban.main.proto.PbUser.PbUserLevelVoOrBuilder getUserLevelVoOrBuilder() {
        if (userLevelVoBuilder_ != null) {
          return userLevelVoBuilder_.getMessageOrBuilder();
        } else {
          return userLevelVo_ == null ?
              com.erban.main.proto.PbUser.PbUserLevelVo.getDefaultInstance() : userLevelVo_;
        }
      }
      /**
       * <code>.allo.proto.PbUserLevelVo userLevelVo = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.erban.main.proto.PbUser.PbUserLevelVo, com.erban.main.proto.PbUser.PbUserLevelVo.Builder, com.erban.main.proto.PbUser.PbUserLevelVoOrBuilder> 
          getUserLevelVoFieldBuilder() {
        if (userLevelVoBuilder_ == null) {
          userLevelVoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.erban.main.proto.PbUser.PbUserLevelVo, com.erban.main.proto.PbUser.PbUserLevelVo.Builder, com.erban.main.proto.PbUser.PbUserLevelVoOrBuilder>(
                  getUserLevelVo(),
                  getParentForChildren(),
                  isClean());
          userLevelVo_ = null;
        }
        return userLevelVoBuilder_;
      }

      private com.erban.main.proto.PbUser.PbUserHeadwearVo userHeadwear_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.erban.main.proto.PbUser.PbUserHeadwearVo, com.erban.main.proto.PbUser.PbUserHeadwearVo.Builder, com.erban.main.proto.PbUser.PbUserHeadwearVoOrBuilder> userHeadwearBuilder_;
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public boolean hasUserHeadwear() {
        return userHeadwearBuilder_ != null || userHeadwear_ != null;
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public com.erban.main.proto.PbUser.PbUserHeadwearVo getUserHeadwear() {
        if (userHeadwearBuilder_ == null) {
          return userHeadwear_ == null ? com.erban.main.proto.PbUser.PbUserHeadwearVo.getDefaultInstance() : userHeadwear_;
        } else {
          return userHeadwearBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public Builder setUserHeadwear(com.erban.main.proto.PbUser.PbUserHeadwearVo value) {
        if (userHeadwearBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userHeadwear_ = value;
          onChanged();
        } else {
          userHeadwearBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public Builder setUserHeadwear(
          com.erban.main.proto.PbUser.PbUserHeadwearVo.Builder builderForValue) {
        if (userHeadwearBuilder_ == null) {
          userHeadwear_ = builderForValue.build();
          onChanged();
        } else {
          userHeadwearBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public Builder mergeUserHeadwear(com.erban.main.proto.PbUser.PbUserHeadwearVo value) {
        if (userHeadwearBuilder_ == null) {
          if (userHeadwear_ != null) {
            userHeadwear_ =
              com.erban.main.proto.PbUser.PbUserHeadwearVo.newBuilder(userHeadwear_).mergeFrom(value).buildPartial();
          } else {
            userHeadwear_ = value;
          }
          onChanged();
        } else {
          userHeadwearBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public Builder clearUserHeadwear() {
        if (userHeadwearBuilder_ == null) {
          userHeadwear_ = null;
          onChanged();
        } else {
          userHeadwear_ = null;
          userHeadwearBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public com.erban.main.proto.PbUser.PbUserHeadwearVo.Builder getUserHeadwearBuilder() {
        
        onChanged();
        return getUserHeadwearFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      public com.erban.main.proto.PbUser.PbUserHeadwearVoOrBuilder getUserHeadwearOrBuilder() {
        if (userHeadwearBuilder_ != null) {
          return userHeadwearBuilder_.getMessageOrBuilder();
        } else {
          return userHeadwear_ == null ?
              com.erban.main.proto.PbUser.PbUserHeadwearVo.getDefaultInstance() : userHeadwear_;
        }
      }
      /**
       * <pre>
       *头饰信息
       * </pre>
       *
       * <code>.allo.proto.PbUserHeadwearVo userHeadwear = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.erban.main.proto.PbUser.PbUserHeadwearVo, com.erban.main.proto.PbUser.PbUserHeadwearVo.Builder, com.erban.main.proto.PbUser.PbUserHeadwearVoOrBuilder> 
          getUserHeadwearFieldBuilder() {
        if (userHeadwearBuilder_ == null) {
          userHeadwearBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.erban.main.proto.PbUser.PbUserHeadwearVo, com.erban.main.proto.PbUser.PbUserHeadwearVo.Builder, com.erban.main.proto.PbUser.PbUserHeadwearVoOrBuilder>(
                  getUserHeadwear(),
                  getParentForChildren(),
                  isClean());
          userHeadwear_ = null;
        }
        return userHeadwearBuilder_;
      }

      private com.erban.main.proto.PbNoble.PbNobleUser nobleUsers_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.erban.main.proto.PbNoble.PbNobleUser, com.erban.main.proto.PbNoble.PbNobleUser.Builder, com.erban.main.proto.PbNoble.PbNobleUserOrBuilder> nobleUsersBuilder_;
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public boolean hasNobleUsers() {
        return nobleUsersBuilder_ != null || nobleUsers_ != null;
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public com.erban.main.proto.PbNoble.PbNobleUser getNobleUsers() {
        if (nobleUsersBuilder_ == null) {
          return nobleUsers_ == null ? com.erban.main.proto.PbNoble.PbNobleUser.getDefaultInstance() : nobleUsers_;
        } else {
          return nobleUsersBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public Builder setNobleUsers(com.erban.main.proto.PbNoble.PbNobleUser value) {
        if (nobleUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nobleUsers_ = value;
          onChanged();
        } else {
          nobleUsersBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public Builder setNobleUsers(
          com.erban.main.proto.PbNoble.PbNobleUser.Builder builderForValue) {
        if (nobleUsersBuilder_ == null) {
          nobleUsers_ = builderForValue.build();
          onChanged();
        } else {
          nobleUsersBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public Builder mergeNobleUsers(com.erban.main.proto.PbNoble.PbNobleUser value) {
        if (nobleUsersBuilder_ == null) {
          if (nobleUsers_ != null) {
            nobleUsers_ =
              com.erban.main.proto.PbNoble.PbNobleUser.newBuilder(nobleUsers_).mergeFrom(value).buildPartial();
          } else {
            nobleUsers_ = value;
          }
          onChanged();
        } else {
          nobleUsersBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public Builder clearNobleUsers() {
        if (nobleUsersBuilder_ == null) {
          nobleUsers_ = null;
          onChanged();
        } else {
          nobleUsers_ = null;
          nobleUsersBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public com.erban.main.proto.PbNoble.PbNobleUser.Builder getNobleUsersBuilder() {
        
        onChanged();
        return getNobleUsersFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      public com.erban.main.proto.PbNoble.PbNobleUserOrBuilder getNobleUsersOrBuilder() {
        if (nobleUsersBuilder_ != null) {
          return nobleUsersBuilder_.getMessageOrBuilder();
        } else {
          return nobleUsers_ == null ?
              com.erban.main.proto.PbNoble.PbNobleUser.getDefaultInstance() : nobleUsers_;
        }
      }
      /**
       * <pre>
       *贵族信息
       * </pre>
       *
       * <code>.allo.proto.PbNobleUser nobleUsers = 17;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.erban.main.proto.PbNoble.PbNobleUser, com.erban.main.proto.PbNoble.PbNobleUser.Builder, com.erban.main.proto.PbNoble.PbNobleUserOrBuilder> 
          getNobleUsersFieldBuilder() {
        if (nobleUsersBuilder_ == null) {
          nobleUsersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.erban.main.proto.PbNoble.PbNobleUser, com.erban.main.proto.PbNoble.PbNobleUser.Builder, com.erban.main.proto.PbNoble.PbNobleUserOrBuilder>(
                  getNobleUsers(),
                  getParentForChildren(),
                  isClean());
          nobleUsers_ = null;
        }
        return nobleUsersBuilder_;
      }

      private int unReadApply_ ;
      /**
       * <pre>
       *未读的申请消息
       * </pre>
       *
       * <code>int32 unReadApply = 18;</code>
       */
      public int getUnReadApply() {
        return unReadApply_;
      }
      /**
       * <pre>
       *未读的申请消息
       * </pre>
       *
       * <code>int32 unReadApply = 18;</code>
       */
      public Builder setUnReadApply(int value) {
        
        unReadApply_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *未读的申请消息
       * </pre>
       *
       * <code>int32 unReadApply = 18;</code>
       */
      public Builder clearUnReadApply() {
        
        unReadApply_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgContent_ = "";
      /**
       * <pre>
       *发送的消息内容
       * </pre>
       *
       * <code>string msgContent = 19;</code>
       */
      public java.lang.String getMsgContent() {
        java.lang.Object ref = msgContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送的消息内容
       * </pre>
       *
       * <code>string msgContent = 19;</code>
       */
      public com.google.protobuf.ByteString
          getMsgContentBytes() {
        java.lang.Object ref = msgContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送的消息内容
       * </pre>
       *
       * <code>string msgContent = 19;</code>
       */
      public Builder setMsgContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的消息内容
       * </pre>
       *
       * <code>string msgContent = 19;</code>
       */
      public Builder clearMsgContent() {
        
        msgContent_ = getDefaultInstance().getMsgContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的消息内容
       * </pre>
       *
       * <code>string msgContent = 19;</code>
       */
      public Builder setMsgContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgContent_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.erban.main.proto.PbUser.PbBadgeUserVo> badgeUserVo_ =
        java.util.Collections.emptyList();
      private void ensureBadgeUserVoIsMutable() {
        if (!((bitField0_ & 0x00080000) != 0)) {
          badgeUserVo_ = new java.util.ArrayList<com.erban.main.proto.PbUser.PbBadgeUserVo>(badgeUserVo_);
          bitField0_ |= 0x00080000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.erban.main.proto.PbUser.PbBadgeUserVo, com.erban.main.proto.PbUser.PbBadgeUserVo.Builder, com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder> badgeUserVoBuilder_;

      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public java.util.List<com.erban.main.proto.PbUser.PbBadgeUserVo> getBadgeUserVoList() {
        if (badgeUserVoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(badgeUserVo_);
        } else {
          return badgeUserVoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public int getBadgeUserVoCount() {
        if (badgeUserVoBuilder_ == null) {
          return badgeUserVo_.size();
        } else {
          return badgeUserVoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public com.erban.main.proto.PbUser.PbBadgeUserVo getBadgeUserVo(int index) {
        if (badgeUserVoBuilder_ == null) {
          return badgeUserVo_.get(index);
        } else {
          return badgeUserVoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder setBadgeUserVo(
          int index, com.erban.main.proto.PbUser.PbBadgeUserVo value) {
        if (badgeUserVoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.set(index, value);
          onChanged();
        } else {
          badgeUserVoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder setBadgeUserVo(
          int index, com.erban.main.proto.PbUser.PbBadgeUserVo.Builder builderForValue) {
        if (badgeUserVoBuilder_ == null) {
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.set(index, builderForValue.build());
          onChanged();
        } else {
          badgeUserVoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder addBadgeUserVo(com.erban.main.proto.PbUser.PbBadgeUserVo value) {
        if (badgeUserVoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.add(value);
          onChanged();
        } else {
          badgeUserVoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder addBadgeUserVo(
          int index, com.erban.main.proto.PbUser.PbBadgeUserVo value) {
        if (badgeUserVoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.add(index, value);
          onChanged();
        } else {
          badgeUserVoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder addBadgeUserVo(
          com.erban.main.proto.PbUser.PbBadgeUserVo.Builder builderForValue) {
        if (badgeUserVoBuilder_ == null) {
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.add(builderForValue.build());
          onChanged();
        } else {
          badgeUserVoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder addBadgeUserVo(
          int index, com.erban.main.proto.PbUser.PbBadgeUserVo.Builder builderForValue) {
        if (badgeUserVoBuilder_ == null) {
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.add(index, builderForValue.build());
          onChanged();
        } else {
          badgeUserVoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder addAllBadgeUserVo(
          java.lang.Iterable<? extends com.erban.main.proto.PbUser.PbBadgeUserVo> values) {
        if (badgeUserVoBuilder_ == null) {
          ensureBadgeUserVoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, badgeUserVo_);
          onChanged();
        } else {
          badgeUserVoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder clearBadgeUserVo() {
        if (badgeUserVoBuilder_ == null) {
          badgeUserVo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00080000);
          onChanged();
        } else {
          badgeUserVoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public Builder removeBadgeUserVo(int index) {
        if (badgeUserVoBuilder_ == null) {
          ensureBadgeUserVoIsMutable();
          badgeUserVo_.remove(index);
          onChanged();
        } else {
          badgeUserVoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public com.erban.main.proto.PbUser.PbBadgeUserVo.Builder getBadgeUserVoBuilder(
          int index) {
        return getBadgeUserVoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder getBadgeUserVoOrBuilder(
          int index) {
        if (badgeUserVoBuilder_ == null) {
          return badgeUserVo_.get(index);  } else {
          return badgeUserVoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public java.util.List<? extends com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder> 
           getBadgeUserVoOrBuilderList() {
        if (badgeUserVoBuilder_ != null) {
          return badgeUserVoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(badgeUserVo_);
        }
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public com.erban.main.proto.PbUser.PbBadgeUserVo.Builder addBadgeUserVoBuilder() {
        return getBadgeUserVoFieldBuilder().addBuilder(
            com.erban.main.proto.PbUser.PbBadgeUserVo.getDefaultInstance());
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public com.erban.main.proto.PbUser.PbBadgeUserVo.Builder addBadgeUserVoBuilder(
          int index) {
        return getBadgeUserVoFieldBuilder().addBuilder(
            index, com.erban.main.proto.PbUser.PbBadgeUserVo.getDefaultInstance());
      }
      /**
       * <code>repeated .allo.proto.PbBadgeUserVo badgeUserVo = 20;</code>
       */
      public java.util.List<com.erban.main.proto.PbUser.PbBadgeUserVo.Builder> 
           getBadgeUserVoBuilderList() {
        return getBadgeUserVoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.erban.main.proto.PbUser.PbBadgeUserVo, com.erban.main.proto.PbUser.PbBadgeUserVo.Builder, com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder> 
          getBadgeUserVoFieldBuilder() {
        if (badgeUserVoBuilder_ == null) {
          badgeUserVoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.erban.main.proto.PbUser.PbBadgeUserVo, com.erban.main.proto.PbUser.PbBadgeUserVo.Builder, com.erban.main.proto.PbUser.PbBadgeUserVoOrBuilder>(
                  badgeUserVo_,
                  ((bitField0_ & 0x00080000) != 0),
                  getParentForChildren(),
                  isClean());
          badgeUserVo_ = null;
        }
        return badgeUserVoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:allo.proto.PbRoomMember)
    }

    // @@protoc_insertion_point(class_scope:allo.proto.PbRoomMember)
    private static final com.erban.main.proto.PbRoomMembers.PbRoomMember DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.erban.main.proto.PbRoomMembers.PbRoomMember();
    }

    public static com.erban.main.proto.PbRoomMembers.PbRoomMember getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PbRoomMember>
        PARSER = new com.google.protobuf.AbstractParser<PbRoomMember>() {
      @java.lang.Override
      public PbRoomMember parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbRoomMember(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbRoomMember> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbRoomMember> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.erban.main.proto.PbRoomMembers.PbRoomMember getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_allo_proto_PbRoomMember_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_allo_proto_PbRoomMember_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025pb_room_members.proto\022\nallo.proto\032\rpb_" +
      "user.proto\032\016pb_noble.proto\"\374\003\n\014PbRoomMem" +
      "ber\022\023\n\013memRecordId\030\001 \001(\003\022\017\n\007roomUid\030\002 \001(" +
      "\003\022\021\n\tmemberUid\030\003 \001(\003\022\024\n\014memberStatus\030\004 \001" +
      "(\005\022\022\n\nmemberRole\030\005 \001(\005\022\021\n\tapplyTime\030\006 \001(" +
      "\003\022\020\n\010joinTime\030\007 \001(\003\022\022\n\nupdateTime\030\010 \001(\003\022" +
      "\017\n\007erbanNo\030\t \001(\003\022\016\n\006avatar\030\n \001(\t\022\014\n\004nick" +
      "\030\013 \001(\t\022\016\n\006gender\030\014 \001(\005\022\r\n\005birth\030\r \001(\003\022\030\n" +
      "\020hasPrettyErbanNo\030\016 \001(\010\022.\n\013userLevelVo\030\017" +
      " \001(\0132\031.allo.proto.PbUserLevelVo\0222\n\014userH" +
      "eadwear\030\020 \001(\0132\034.allo.proto.PbUserHeadwea" +
      "rVo\022+\n\nnobleUsers\030\021 \001(\0132\027.allo.proto.PbN" +
      "obleUser\022\023\n\013unReadApply\030\022 \001(\005\022\022\n\nmsgCont" +
      "ent\030\023 \001(\t\022.\n\013badgeUserVo\030\024 \003(\0132\031.allo.pr" +
      "oto.PbBadgeUserVoB\026\n\024com.erban.main.prot" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.erban.main.proto.PbUser.getDescriptor(),
          com.erban.main.proto.PbNoble.getDescriptor(),
        }, assigner);
    internal_static_allo_proto_PbRoomMember_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_allo_proto_PbRoomMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_allo_proto_PbRoomMember_descriptor,
        new java.lang.String[] { "MemRecordId", "RoomUid", "MemberUid", "MemberStatus", "MemberRole", "ApplyTime", "JoinTime", "UpdateTime", "ErbanNo", "Avatar", "Nick", "Gender", "Birth", "HasPrettyErbanNo", "UserLevelVo", "UserHeadwear", "NobleUsers", "UnReadApply", "MsgContent", "BadgeUserVo", });
    com.erban.main.proto.PbUser.getDescriptor();
    com.erban.main.proto.PbNoble.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
