logging.config: classpath:logback-test.xml

app.product: false
logs.level: INFO

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 172.26.225.10:8848
        namespace: 817845f5-4ca6-4ae3-bfcd-72a018ba2e25
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes: 172.26.225.2:7001,172.26.225.2:7002,172.26.225.2:7003
    password: bwgfs127BWGFS127
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000ms
        max-idle: 8
        min-idle: 0
  kafka:
    bootstrap-servers: 172.26.225.2:9092
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 1
    consumer:
      auto-offset-reset: latest
      group-id: allo-finance-service-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  shardingsphere:
    datasource:
      names: master,slave0
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/finance?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: nswqSA@@$S113dd(()
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/finance?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: udskk
        password: nswqSA@@$S113dd(()
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: master,slave0
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#nacos整合i18n配置
i18n:
  nacos:
    config:
      server-addr: 172.26.225.10:8848
      namespace: 5f231fd0-1be1-4187-9465-1c5d0bc39210
      group: i18n-prod
      dataIds: messages.properties,messages_en.properties,messages_ar.properties,messages_tr.properties,messages_in.properties,messages_zh.properties
